// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See Vascon_top.h for the primary calling header

#ifndef VERILATED_VASCON_TOP___024ROOT_H_
#define VERILATED_VASCON_TOP___024ROOT_H_  // guard

#include "verilated.h"
class Vascon_top_ascon_sbox_d2;


class Vascon_top__Syms;

class alignas(VL_CACHE_LINE_BYTES) Vascon_top___024root final : public VerilatedModule {
  public:
    // CELLS
    Vascon_top_ascon_sbox_d2* __PVT__ascon_top__DOT__gen_cog__DOT__gen_sbox__BRA__0__KET____DOT__u_sbox;
    Vascon_top_ascon_sbox_d2* __PVT__ascon_top__DOT__gen_cog__DOT__gen_sbox__BRA__1__KET____DOT__u_sbox;
    Vascon_top_ascon_sbox_d2* __PVT__ascon_top__DOT__gen_cog__DOT__gen_sbox__BRA__2__KET____DOT__u_sbox;
    Vascon_top_ascon_sbox_d2* __PVT__ascon_top__DOT__gen_cog__DOT__gen_sbox__BRA__3__KET____DOT__u_sbox;
    Vascon_top_ascon_sbox_d2* __PVT__ascon_top__DOT__gen_cog__DOT__gen_sbox__BRA__4__KET____DOT__u_sbox;
    Vascon_top_ascon_sbox_d2* __PVT__ascon_top__DOT__gen_cog__DOT__gen_sbox__BRA__5__KET____DOT__u_sbox;
    Vascon_top_ascon_sbox_d2* __PVT__ascon_top__DOT__gen_cog__DOT__gen_sbox__BRA__6__KET____DOT__u_sbox;
    Vascon_top_ascon_sbox_d2* __PVT__ascon_top__DOT__gen_cog__DOT__gen_sbox__BRA__7__KET____DOT__u_sbox;
    Vascon_top_ascon_sbox_d2* __PVT__ascon_top__DOT__gen_cog__DOT__gen_sbox__BRA__8__KET____DOT__u_sbox;
    Vascon_top_ascon_sbox_d2* __PVT__ascon_top__DOT__gen_cog__DOT__gen_sbox__BRA__9__KET____DOT__u_sbox;
    Vascon_top_ascon_sbox_d2* __PVT__ascon_top__DOT__gen_cog__DOT__gen_sbox__BRA__10__KET____DOT__u_sbox;
    Vascon_top_ascon_sbox_d2* __PVT__ascon_top__DOT__gen_cog__DOT__gen_sbox__BRA__11__KET____DOT__u_sbox;
    Vascon_top_ascon_sbox_d2* __PVT__ascon_top__DOT__gen_cog__DOT__gen_sbox__BRA__12__KET____DOT__u_sbox;
    Vascon_top_ascon_sbox_d2* __PVT__ascon_top__DOT__gen_cog__DOT__gen_sbox__BRA__13__KET____DOT__u_sbox;
    Vascon_top_ascon_sbox_d2* __PVT__ascon_top__DOT__gen_cog__DOT__gen_sbox__BRA__14__KET____DOT__u_sbox;
    Vascon_top_ascon_sbox_d2* __PVT__ascon_top__DOT__gen_cog__DOT__gen_sbox__BRA__15__KET____DOT__u_sbox;
    Vascon_top_ascon_sbox_d2* __PVT__ascon_top__DOT__gen_cog__DOT__gen_sbox__BRA__16__KET____DOT__u_sbox;
    Vascon_top_ascon_sbox_d2* __PVT__ascon_top__DOT__gen_cog__DOT__gen_sbox__BRA__17__KET____DOT__u_sbox;
    Vascon_top_ascon_sbox_d2* __PVT__ascon_top__DOT__gen_cog__DOT__gen_sbox__BRA__18__KET____DOT__u_sbox;
    Vascon_top_ascon_sbox_d2* __PVT__ascon_top__DOT__gen_cog__DOT__gen_sbox__BRA__19__KET____DOT__u_sbox;
    Vascon_top_ascon_sbox_d2* __PVT__ascon_top__DOT__gen_cog__DOT__gen_sbox__BRA__20__KET____DOT__u_sbox;
    Vascon_top_ascon_sbox_d2* __PVT__ascon_top__DOT__gen_cog__DOT__gen_sbox__BRA__21__KET____DOT__u_sbox;

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        VL_IN8(clk,0,0);
        VL_IN8(reset_n,0,0);
        VL_IN8(start,0,0);
        VL_IN8(key_valid,0,0);
        VL_IN8(valid_data_in,0,0);
        VL_IN8(last_block,0,0);
        VL_IN8(valid_bytes,3,0);
        VL_IN8(EOT,0,0);
        VL_IN8(random_masks_sbox,2,0);
        VL_OUT8(ciphertext_valid,0,0);
        VL_OUT8(done,0,0);
        VL_OUT8(ready_tag,0,0);
        VL_OUT8(ready_for_data,0,0);
        VL_OUT8(debug_extra_padding_ff,0,0);
        VL_OUT8(debug_bitcounter,2,0);
        VL_OUT8(debug_roundcounter,3,0);
        VL_OUT8(debug_state,4,0);
        CData/*0:0*/ ascon_top__DOT__shift_en;
        CData/*0:0*/ ascon_top__DOT__shift_type;
        CData/*0:0*/ ascon_top__DOT__write_en;
        CData/*0:0*/ ascon_top__DOT__last_cycle;
        CData/*0:0*/ ascon_top__DOT__reg_key1_load;
        CData/*0:0*/ ascon_top__DOT__reg_key2_load;
        CData/*0:0*/ ascon_top__DOT__sel_mux_linear_diffusion_out_x3;
        CData/*0:0*/ ascon_top__DOT__sel_mux_linear_diffusion_out_x4;
        CData/*0:0*/ ascon_top__DOT__sel_init_load;
        CData/*0:0*/ ascon_top__DOT__sel_masked_round;
        CData/*0:0*/ ascon_top__DOT__sel_padding;
        CData/*0:0*/ ascon_top__DOT__sel_xor_signal;
        CData/*0:0*/ ascon_top__DOT__sel_absorb_data;
        CData/*0:0*/ ascon_top__DOT__extra_padding;
        CData/*0:0*/ ascon_top__DOT__shift_enable_sipo;
        CData/*0:0*/ ascon_top__DOT__last_cycle_sipo;
        CData/*3:0*/ ascon_top__DOT__round_counter;
        CData/*2:0*/ ascon_top__DOT__bit_counter;
        CData/*2:0*/ ascon_top__DOT__fresh_r;
        CData/*2:0*/ ascon_top__DOT__recombine__BRA__0__KET____DOT__temp_bits;
        CData/*2:0*/ ascon_top__DOT__recombine__BRA__1__KET____DOT__temp_bits;
        CData/*2:0*/ ascon_top__DOT__recombine__BRA__2__KET____DOT__temp_bits;
        CData/*2:0*/ ascon_top__DOT__recombine__BRA__3__KET____DOT__temp_bits;
        CData/*2:0*/ ascon_top__DOT__recombine__BRA__4__KET____DOT__temp_bits;
        CData/*2:0*/ ascon_top__DOT__recombine__BRA__5__KET____DOT__temp_bits;
        CData/*2:0*/ ascon_top__DOT__recombine__BRA__6__KET____DOT__temp_bits;
        CData/*2:0*/ ascon_top__DOT__recombine__BRA__7__KET____DOT__temp_bits;
        CData/*2:0*/ ascon_top__DOT__recombine__BRA__8__KET____DOT__temp_bits;
        CData/*2:0*/ ascon_top__DOT__recombine__BRA__9__KET____DOT__temp_bits;
        CData/*2:0*/ ascon_top__DOT__recombine__BRA__10__KET____DOT__temp_bits;
        CData/*2:0*/ ascon_top__DOT__recombine__BRA__11__KET____DOT__temp_bits;
        CData/*2:0*/ ascon_top__DOT__recombine__BRA__12__KET____DOT__temp_bits;
        CData/*2:0*/ ascon_top__DOT__recombine__BRA__13__KET____DOT__temp_bits;
        CData/*2:0*/ ascon_top__DOT__recombine__BRA__14__KET____DOT__temp_bits;
        CData/*2:0*/ ascon_top__DOT__recombine__BRA__15__KET____DOT__temp_bits;
        CData/*2:0*/ ascon_top__DOT__recombine__BRA__16__KET____DOT__temp_bits;
        CData/*2:0*/ ascon_top__DOT__recombine__BRA__17__KET____DOT__temp_bits;
        CData/*2:0*/ ascon_top__DOT__recombine__BRA__18__KET____DOT__temp_bits;
        CData/*2:0*/ ascon_top__DOT__recombine__BRA__19__KET____DOT__temp_bits;
        CData/*2:0*/ ascon_top__DOT__recombine__BRA__20__KET____DOT__temp_bits;
        CData/*2:0*/ ascon_top__DOT__recombine__BRA__21__KET____DOT__temp_bits;
        CData/*2:0*/ ascon_top__DOT__recombine__BRA__22__KET____DOT__temp_bits;
        CData/*2:0*/ ascon_top__DOT__recombine__BRA__23__KET____DOT__temp_bits;
        CData/*2:0*/ ascon_top__DOT__recombine__BRA__24__KET____DOT__temp_bits;
        CData/*2:0*/ ascon_top__DOT__recombine__BRA__25__KET____DOT__temp_bits;
        CData/*2:0*/ ascon_top__DOT__recombine__BRA__26__KET____DOT__temp_bits;
        CData/*2:0*/ ascon_top__DOT__recombine__BRA__27__KET____DOT__temp_bits;
    };
    struct {
        CData/*2:0*/ ascon_top__DOT__recombine__BRA__28__KET____DOT__temp_bits;
        CData/*2:0*/ ascon_top__DOT__recombine__BRA__29__KET____DOT__temp_bits;
        CData/*2:0*/ ascon_top__DOT__recombine__BRA__30__KET____DOT__temp_bits;
        CData/*2:0*/ ascon_top__DOT__recombine__BRA__31__KET____DOT__temp_bits;
        CData/*2:0*/ ascon_top__DOT__recombine__BRA__32__KET____DOT__temp_bits;
        CData/*2:0*/ ascon_top__DOT__recombine__BRA__33__KET____DOT__temp_bits;
        CData/*2:0*/ ascon_top__DOT__recombine__BRA__34__KET____DOT__temp_bits;
        CData/*2:0*/ ascon_top__DOT__recombine__BRA__35__KET____DOT__temp_bits;
        CData/*2:0*/ ascon_top__DOT__recombine__BRA__36__KET____DOT__temp_bits;
        CData/*2:0*/ ascon_top__DOT__recombine__BRA__37__KET____DOT__temp_bits;
        CData/*2:0*/ ascon_top__DOT__recombine__BRA__38__KET____DOT__temp_bits;
        CData/*2:0*/ ascon_top__DOT__recombine__BRA__39__KET____DOT__temp_bits;
        CData/*2:0*/ ascon_top__DOT__recombine__BRA__40__KET____DOT__temp_bits;
        CData/*2:0*/ ascon_top__DOT__recombine__BRA__41__KET____DOT__temp_bits;
        CData/*2:0*/ ascon_top__DOT__recombine__BRA__42__KET____DOT__temp_bits;
        CData/*2:0*/ ascon_top__DOT__recombine__BRA__43__KET____DOT__temp_bits;
        CData/*2:0*/ ascon_top__DOT__recombine__BRA__44__KET____DOT__temp_bits;
        CData/*2:0*/ ascon_top__DOT__recombine__BRA__45__KET____DOT__temp_bits;
        CData/*2:0*/ ascon_top__DOT__recombine__BRA__46__KET____DOT__temp_bits;
        CData/*2:0*/ ascon_top__DOT__recombine__BRA__47__KET____DOT__temp_bits;
        CData/*2:0*/ ascon_top__DOT__recombine__BRA__48__KET____DOT__temp_bits;
        CData/*2:0*/ ascon_top__DOT__recombine__BRA__49__KET____DOT__temp_bits;
        CData/*2:0*/ ascon_top__DOT__recombine__BRA__50__KET____DOT__temp_bits;
        CData/*2:0*/ ascon_top__DOT__recombine__BRA__51__KET____DOT__temp_bits;
        CData/*2:0*/ ascon_top__DOT__recombine__BRA__52__KET____DOT__temp_bits;
        CData/*2:0*/ ascon_top__DOT__recombine__BRA__53__KET____DOT__temp_bits;
        CData/*2:0*/ ascon_top__DOT__recombine__BRA__54__KET____DOT__temp_bits;
        CData/*2:0*/ ascon_top__DOT__recombine__BRA__55__KET____DOT__temp_bits;
        CData/*2:0*/ ascon_top__DOT__recombine__BRA__56__KET____DOT__temp_bits;
        CData/*2:0*/ ascon_top__DOT__recombine__BRA__57__KET____DOT__temp_bits;
        CData/*2:0*/ ascon_top__DOT__recombine__BRA__58__KET____DOT__temp_bits;
        CData/*2:0*/ ascon_top__DOT__recombine__BRA__59__KET____DOT__temp_bits;
        CData/*2:0*/ ascon_top__DOT__recombine__BRA__60__KET____DOT__temp_bits;
        CData/*2:0*/ ascon_top__DOT__recombine__BRA__61__KET____DOT__temp_bits;
        CData/*2:0*/ ascon_top__DOT__recombine__BRA__62__KET____DOT__temp_bits;
        CData/*2:0*/ ascon_top__DOT__recombine__BRA__63__KET____DOT__temp_bits;
        CData/*2:0*/ ascon_top__DOT__recombine__BRA__64__KET____DOT__temp_bits;
        CData/*2:0*/ ascon_top__DOT__recombine__BRA__65__KET____DOT__temp_bits;
        CData/*2:0*/ ascon_top__DOT__recombine__BRA__66__KET____DOT__temp_bits;
        CData/*2:0*/ ascon_top__DOT__recombine__BRA__67__KET____DOT__temp_bits;
        CData/*2:0*/ ascon_top__DOT__recombine__BRA__68__KET____DOT__temp_bits;
        CData/*2:0*/ ascon_top__DOT__recombine__BRA__69__KET____DOT__temp_bits;
        CData/*2:0*/ ascon_top__DOT__recombine__BRA__70__KET____DOT__temp_bits;
        CData/*2:0*/ ascon_top__DOT__recombine__BRA__71__KET____DOT__temp_bits;
        CData/*2:0*/ ascon_top__DOT__recombine__BRA__72__KET____DOT__temp_bits;
        CData/*2:0*/ ascon_top__DOT__recombine__BRA__73__KET____DOT__temp_bits;
        CData/*2:0*/ ascon_top__DOT__recombine__BRA__74__KET____DOT__temp_bits;
        CData/*2:0*/ ascon_top__DOT__recombine__BRA__75__KET____DOT__temp_bits;
        CData/*2:0*/ ascon_top__DOT__recombine__BRA__76__KET____DOT__temp_bits;
        CData/*2:0*/ ascon_top__DOT__recombine__BRA__77__KET____DOT__temp_bits;
        CData/*2:0*/ ascon_top__DOT__recombine__BRA__78__KET____DOT__temp_bits;
        CData/*2:0*/ ascon_top__DOT__recombine__BRA__79__KET____DOT__temp_bits;
        CData/*2:0*/ ascon_top__DOT__recombine__BRA__80__KET____DOT__temp_bits;
        CData/*2:0*/ ascon_top__DOT__recombine__BRA__81__KET____DOT__temp_bits;
        CData/*2:0*/ ascon_top__DOT__recombine__BRA__82__KET____DOT__temp_bits;
        CData/*2:0*/ ascon_top__DOT__recombine__BRA__83__KET____DOT__temp_bits;
        CData/*2:0*/ ascon_top__DOT__recombine__BRA__84__KET____DOT__temp_bits;
        CData/*2:0*/ ascon_top__DOT__recombine__BRA__85__KET____DOT__temp_bits;
        CData/*2:0*/ ascon_top__DOT__recombine__BRA__86__KET____DOT__temp_bits;
        CData/*2:0*/ ascon_top__DOT__recombine__BRA__87__KET____DOT__temp_bits;
        CData/*2:0*/ ascon_top__DOT__recombine__BRA__88__KET____DOT__temp_bits;
        CData/*2:0*/ ascon_top__DOT__recombine__BRA__89__KET____DOT__temp_bits;
        CData/*2:0*/ ascon_top__DOT__recombine__BRA__90__KET____DOT__temp_bits;
        CData/*2:0*/ ascon_top__DOT__recombine__BRA__91__KET____DOT__temp_bits;
    };
    struct {
        CData/*2:0*/ ascon_top__DOT__recombine__BRA__92__KET____DOT__temp_bits;
        CData/*2:0*/ ascon_top__DOT__recombine__BRA__93__KET____DOT__temp_bits;
        CData/*2:0*/ ascon_top__DOT__recombine__BRA__94__KET____DOT__temp_bits;
        CData/*2:0*/ ascon_top__DOT__recombine__BRA__95__KET____DOT__temp_bits;
        CData/*2:0*/ ascon_top__DOT__recombine__BRA__96__KET____DOT__temp_bits;
        CData/*2:0*/ ascon_top__DOT__recombine__BRA__97__KET____DOT__temp_bits;
        CData/*2:0*/ ascon_top__DOT__recombine__BRA__98__KET____DOT__temp_bits;
        CData/*2:0*/ ascon_top__DOT__recombine__BRA__99__KET____DOT__temp_bits;
        CData/*2:0*/ ascon_top__DOT__recombine__BRA__100__KET____DOT__temp_bits;
        CData/*2:0*/ ascon_top__DOT__recombine__BRA__101__KET____DOT__temp_bits;
        CData/*2:0*/ ascon_top__DOT__recombine__BRA__102__KET____DOT__temp_bits;
        CData/*2:0*/ ascon_top__DOT__recombine__BRA__103__KET____DOT__temp_bits;
        CData/*2:0*/ ascon_top__DOT__recombine__BRA__104__KET____DOT__temp_bits;
        CData/*2:0*/ ascon_top__DOT__recombine__BRA__105__KET____DOT__temp_bits;
        CData/*2:0*/ ascon_top__DOT__recombine__BRA__106__KET____DOT__temp_bits;
        CData/*2:0*/ ascon_top__DOT__recombine__BRA__107__KET____DOT__temp_bits;
        CData/*2:0*/ ascon_top__DOT__recombine__BRA__108__KET____DOT__temp_bits;
        CData/*2:0*/ ascon_top__DOT__recombine__BRA__109__KET____DOT__temp_bits;
        CData/*0:0*/ ascon_top__DOT____Vlvbound_h438ededb__0;
        CData/*0:0*/ ascon_top__DOT____Vlvbound_hfe1f1a3f__0;
        CData/*0:0*/ ascon_top__DOT____Vlvbound_h56f822d7__0;
        CData/*4:0*/ ascon_top__DOT__mealy_fsm__DOT__current_state;
        CData/*4:0*/ ascon_top__DOT__mealy_fsm__DOT__next_state;
        CData/*2:0*/ ascon_top__DOT__mealy_fsm__DOT__number_bits;
        CData/*3:0*/ ascon_top__DOT__mealy_fsm__DOT__number_round;
        CData/*0:0*/ ascon_top__DOT__mealy_fsm__DOT__last_block_process;
        CData/*0:0*/ ascon_top__DOT__mealy_fsm__DOT__last_block_process_ff;
        CData/*0:0*/ ascon_top__DOT__mealy_fsm__DOT__last_block_process_load;
        CData/*0:0*/ ascon_top__DOT__mealy_fsm__DOT__extra_padding_load;
        CData/*0:0*/ ascon_top__DOT__mealy_fsm__DOT__round_counter_enable;
        CData/*0:0*/ ascon_top__DOT__mealy_fsm__DOT__rst_counter_round;
        CData/*0:0*/ __VstlFirstIteration;
        CData/*0:0*/ __VicoFirstIteration;
        CData/*0:0*/ __Vtrigprevexpr___TOP__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__reset_n__0;
        CData/*0:0*/ __VactContinue;
        VL_INW(data_in,127,0,4);
        VL_INW(random_masks,219,0,7);
        VL_OUTW(ciphertext,127,0,4);
        VlWide<10>/*319:0*/ ascon_top__DOT__state_reg_out;
        VlWide<10>/*319:0*/ ascon_top__DOT__state_reg_in;
        VlWide<10>/*319:0*/ ascon_top__DOT__state_reg_out_shiftdplus1;
        VlWide<10>/*319:0*/ ascon_top__DOT__state_reg_in_shiftdplus1;
        IData/*21:0*/ ascon_top__DOT____Vcellinp__sipo_reg_x2_debug__in_shifted_1bit;
        VlWide<11>/*329:0*/ ascon_top__DOT__shares_out;
        VlWide<4>/*109:0*/ ascon_top__DOT__shares_in;
        VlWide<4>/*109:0*/ ascon_top__DOT__recombine_shares;
        VlWide<4>/*127:0*/ ascon_top__DOT__data_in_padded;
        VlWide<4>/*127:0*/ ascon_top__DOT__reverse_reg_data_out;
        IData/*31:0*/ ascon_top__DOT__unnamedblk1__DOT__p;
        IData/*31:0*/ ascon_top__DOT__unnamedblk5__DOT__i;
        VlWide<6>/*191:0*/ ascon_top__DOT____VdfgRegularize_h0932e10f_2_0;
        IData/*21:0*/ ascon_top__DOT____VdfgRegularize_h0932e10f_3_3;
        IData/*21:0*/ ascon_top__DOT____VdfgRegularize_h0932e10f_3_5;
        IData/*21:0*/ ascon_top__DOT____VdfgRegularize_h0932e10f_3_6;
        IData/*21:0*/ ascon_top__DOT____VdfgRegularize_h0932e10f_3_8;
        IData/*21:0*/ ascon_top__DOT____VdfgRegularize_h0932e10f_3_9;
        IData/*31:0*/ ascon_top__DOT__state_reg__DOT__unnamedblk3__DOT__i;
        VlWide<4>/*109:0*/ ascon_top__DOT__share_creator__DOT__temp;
        IData/*31:0*/ __Vfunc_ascon_top__DOT__xor_tree__0__unnamedblk3__DOT__i;
        IData/*31:0*/ __Vfunc_ascon_top__DOT__xor_tree__1__unnamedblk3__DOT__i;
        IData/*31:0*/ __Vfunc_ascon_top__DOT__xor_tree__2__unnamedblk3__DOT__i;
        IData/*31:0*/ __Vfunc_ascon_top__DOT__xor_tree__3__unnamedblk3__DOT__i;
        IData/*31:0*/ __Vfunc_ascon_top__DOT__xor_tree__4__unnamedblk3__DOT__i;
    };
    struct {
        IData/*31:0*/ __Vfunc_ascon_top__DOT__xor_tree__5__unnamedblk3__DOT__i;
        IData/*31:0*/ __Vfunc_ascon_top__DOT__xor_tree__6__unnamedblk3__DOT__i;
        IData/*31:0*/ __Vfunc_ascon_top__DOT__xor_tree__7__unnamedblk3__DOT__i;
        IData/*31:0*/ __Vfunc_ascon_top__DOT__xor_tree__8__unnamedblk3__DOT__i;
        IData/*31:0*/ __Vfunc_ascon_top__DOT__xor_tree__9__unnamedblk3__DOT__i;
        IData/*31:0*/ __Vfunc_ascon_top__DOT__xor_tree__10__unnamedblk3__DOT__i;
        IData/*31:0*/ __Vfunc_ascon_top__DOT__xor_tree__11__unnamedblk3__DOT__i;
        IData/*31:0*/ __Vfunc_ascon_top__DOT__xor_tree__12__unnamedblk3__DOT__i;
        IData/*31:0*/ __Vfunc_ascon_top__DOT__xor_tree__13__unnamedblk3__DOT__i;
        IData/*31:0*/ __Vfunc_ascon_top__DOT__xor_tree__14__unnamedblk3__DOT__i;
        IData/*31:0*/ __Vfunc_ascon_top__DOT__xor_tree__15__unnamedblk3__DOT__i;
        IData/*31:0*/ __Vfunc_ascon_top__DOT__xor_tree__16__unnamedblk3__DOT__i;
        IData/*31:0*/ __Vfunc_ascon_top__DOT__xor_tree__17__unnamedblk3__DOT__i;
        IData/*31:0*/ __Vfunc_ascon_top__DOT__xor_tree__18__unnamedblk3__DOT__i;
        IData/*31:0*/ __Vfunc_ascon_top__DOT__xor_tree__19__unnamedblk3__DOT__i;
        IData/*31:0*/ __Vfunc_ascon_top__DOT__xor_tree__20__unnamedblk3__DOT__i;
        IData/*31:0*/ __Vfunc_ascon_top__DOT__xor_tree__21__unnamedblk3__DOT__i;
        IData/*31:0*/ __Vfunc_ascon_top__DOT__xor_tree__22__unnamedblk3__DOT__i;
        IData/*31:0*/ __Vfunc_ascon_top__DOT__xor_tree__23__unnamedblk3__DOT__i;
        IData/*31:0*/ __Vfunc_ascon_top__DOT__xor_tree__24__unnamedblk3__DOT__i;
        IData/*31:0*/ __Vfunc_ascon_top__DOT__xor_tree__25__unnamedblk3__DOT__i;
        IData/*31:0*/ __Vfunc_ascon_top__DOT__xor_tree__26__unnamedblk3__DOT__i;
        IData/*31:0*/ __Vfunc_ascon_top__DOT__xor_tree__27__unnamedblk3__DOT__i;
        IData/*31:0*/ __Vfunc_ascon_top__DOT__xor_tree__28__unnamedblk3__DOT__i;
        IData/*31:0*/ __Vfunc_ascon_top__DOT__xor_tree__29__unnamedblk3__DOT__i;
        IData/*31:0*/ __Vfunc_ascon_top__DOT__xor_tree__30__unnamedblk3__DOT__i;
        IData/*31:0*/ __Vfunc_ascon_top__DOT__xor_tree__31__unnamedblk3__DOT__i;
        IData/*31:0*/ __Vfunc_ascon_top__DOT__xor_tree__32__unnamedblk3__DOT__i;
        IData/*31:0*/ __Vfunc_ascon_top__DOT__xor_tree__33__unnamedblk3__DOT__i;
        IData/*31:0*/ __Vfunc_ascon_top__DOT__xor_tree__34__unnamedblk3__DOT__i;
        IData/*31:0*/ __Vfunc_ascon_top__DOT__xor_tree__35__unnamedblk3__DOT__i;
        IData/*31:0*/ __Vfunc_ascon_top__DOT__xor_tree__36__unnamedblk3__DOT__i;
        IData/*31:0*/ __Vfunc_ascon_top__DOT__xor_tree__37__unnamedblk3__DOT__i;
        IData/*31:0*/ __Vfunc_ascon_top__DOT__xor_tree__38__unnamedblk3__DOT__i;
        IData/*31:0*/ __Vfunc_ascon_top__DOT__xor_tree__39__unnamedblk3__DOT__i;
        IData/*31:0*/ __Vfunc_ascon_top__DOT__xor_tree__40__unnamedblk3__DOT__i;
        IData/*31:0*/ __Vfunc_ascon_top__DOT__xor_tree__41__unnamedblk3__DOT__i;
        IData/*31:0*/ __Vfunc_ascon_top__DOT__xor_tree__41__level;
        IData/*31:0*/ __Vfunc_ascon_top__DOT__xor_tree__42__unnamedblk3__DOT__i;
        IData/*31:0*/ __Vfunc_ascon_top__DOT__xor_tree__42__level;
        IData/*31:0*/ __Vfunc_ascon_top__DOT__xor_tree__43__unnamedblk3__DOT__i;
        IData/*31:0*/ __Vfunc_ascon_top__DOT__xor_tree__44__unnamedblk3__DOT__i;
        IData/*31:0*/ __Vfunc_ascon_top__DOT__xor_tree__45__unnamedblk3__DOT__i;
        IData/*31:0*/ __Vfunc_ascon_top__DOT__xor_tree__46__unnamedblk3__DOT__i;
        IData/*31:0*/ __Vfunc_ascon_top__DOT__xor_tree__47__unnamedblk3__DOT__i;
        IData/*31:0*/ __Vfunc_ascon_top__DOT__xor_tree__48__unnamedblk3__DOT__i;
        IData/*31:0*/ __Vfunc_ascon_top__DOT__xor_tree__49__unnamedblk3__DOT__i;
        IData/*31:0*/ __Vfunc_ascon_top__DOT__xor_tree__50__unnamedblk3__DOT__i;
        IData/*31:0*/ __Vfunc_ascon_top__DOT__xor_tree__51__unnamedblk3__DOT__i;
        IData/*31:0*/ __Vfunc_ascon_top__DOT__xor_tree__52__unnamedblk3__DOT__i;
        IData/*31:0*/ __Vfunc_ascon_top__DOT__xor_tree__53__unnamedblk3__DOT__i;
        IData/*31:0*/ __Vfunc_ascon_top__DOT__xor_tree__54__unnamedblk3__DOT__i;
        IData/*31:0*/ __Vfunc_ascon_top__DOT__xor_tree__55__unnamedblk3__DOT__i;
        IData/*31:0*/ __Vfunc_ascon_top__DOT__xor_tree__56__unnamedblk3__DOT__i;
        IData/*31:0*/ __Vfunc_ascon_top__DOT__xor_tree__57__unnamedblk3__DOT__i;
        IData/*31:0*/ __Vfunc_ascon_top__DOT__xor_tree__58__unnamedblk3__DOT__i;
        IData/*31:0*/ __Vfunc_ascon_top__DOT__xor_tree__59__unnamedblk3__DOT__i;
        IData/*31:0*/ __Vfunc_ascon_top__DOT__xor_tree__60__unnamedblk3__DOT__i;
        IData/*31:0*/ __Vfunc_ascon_top__DOT__xor_tree__61__unnamedblk3__DOT__i;
        IData/*31:0*/ __Vfunc_ascon_top__DOT__xor_tree__62__unnamedblk3__DOT__i;
        IData/*31:0*/ __Vfunc_ascon_top__DOT__xor_tree__63__unnamedblk3__DOT__i;
        IData/*31:0*/ __Vfunc_ascon_top__DOT__xor_tree__64__unnamedblk3__DOT__i;
        IData/*31:0*/ __Vfunc_ascon_top__DOT__xor_tree__65__unnamedblk3__DOT__i;
        IData/*31:0*/ __Vfunc_ascon_top__DOT__xor_tree__66__unnamedblk3__DOT__i;
    };
    struct {
        IData/*31:0*/ __Vfunc_ascon_top__DOT__xor_tree__67__unnamedblk3__DOT__i;
        IData/*31:0*/ __Vfunc_ascon_top__DOT__xor_tree__68__unnamedblk3__DOT__i;
        IData/*31:0*/ __Vfunc_ascon_top__DOT__xor_tree__69__unnamedblk3__DOT__i;
        IData/*31:0*/ __Vfunc_ascon_top__DOT__xor_tree__70__unnamedblk3__DOT__i;
        IData/*31:0*/ __Vfunc_ascon_top__DOT__xor_tree__71__unnamedblk3__DOT__i;
        IData/*31:0*/ __Vfunc_ascon_top__DOT__xor_tree__72__unnamedblk3__DOT__i;
        IData/*31:0*/ __Vfunc_ascon_top__DOT__xor_tree__73__unnamedblk3__DOT__i;
        IData/*31:0*/ __Vfunc_ascon_top__DOT__xor_tree__74__unnamedblk3__DOT__i;
        IData/*31:0*/ __Vfunc_ascon_top__DOT__xor_tree__75__unnamedblk3__DOT__i;
        IData/*31:0*/ __Vfunc_ascon_top__DOT__xor_tree__76__unnamedblk3__DOT__i;
        IData/*31:0*/ __Vfunc_ascon_top__DOT__xor_tree__77__unnamedblk3__DOT__i;
        IData/*31:0*/ __Vfunc_ascon_top__DOT__xor_tree__78__unnamedblk3__DOT__i;
        IData/*31:0*/ __Vfunc_ascon_top__DOT__xor_tree__79__unnamedblk3__DOT__i;
        IData/*31:0*/ __Vfunc_ascon_top__DOT__xor_tree__80__unnamedblk3__DOT__i;
        IData/*31:0*/ __Vfunc_ascon_top__DOT__xor_tree__81__unnamedblk3__DOT__i;
        IData/*31:0*/ __Vfunc_ascon_top__DOT__xor_tree__82__unnamedblk3__DOT__i;
        IData/*31:0*/ __Vfunc_ascon_top__DOT__xor_tree__83__unnamedblk3__DOT__i;
        IData/*31:0*/ __Vfunc_ascon_top__DOT__xor_tree__84__unnamedblk3__DOT__i;
        IData/*31:0*/ __Vfunc_ascon_top__DOT__xor_tree__85__unnamedblk3__DOT__i;
        IData/*31:0*/ __Vfunc_ascon_top__DOT__xor_tree__86__unnamedblk3__DOT__i;
        IData/*31:0*/ __Vfunc_ascon_top__DOT__xor_tree__87__unnamedblk3__DOT__i;
        IData/*31:0*/ __Vfunc_ascon_top__DOT__xor_tree__88__unnamedblk3__DOT__i;
        IData/*31:0*/ __Vfunc_ascon_top__DOT__xor_tree__89__unnamedblk3__DOT__i;
        IData/*31:0*/ __Vfunc_ascon_top__DOT__xor_tree__90__unnamedblk3__DOT__i;
        IData/*31:0*/ __Vfunc_ascon_top__DOT__xor_tree__91__unnamedblk3__DOT__i;
        IData/*31:0*/ __Vfunc_ascon_top__DOT__xor_tree__92__unnamedblk3__DOT__i;
        IData/*31:0*/ __Vfunc_ascon_top__DOT__xor_tree__93__unnamedblk3__DOT__i;
        IData/*31:0*/ __Vfunc_ascon_top__DOT__xor_tree__94__unnamedblk3__DOT__i;
        IData/*31:0*/ __Vfunc_ascon_top__DOT__xor_tree__95__unnamedblk3__DOT__i;
        IData/*31:0*/ __Vfunc_ascon_top__DOT__xor_tree__96__unnamedblk3__DOT__i;
        IData/*31:0*/ __Vfunc_ascon_top__DOT__xor_tree__97__unnamedblk3__DOT__i;
        IData/*31:0*/ __Vfunc_ascon_top__DOT__xor_tree__98__unnamedblk3__DOT__i;
        IData/*31:0*/ __Vfunc_ascon_top__DOT__xor_tree__99__unnamedblk3__DOT__i;
        IData/*31:0*/ __Vfunc_ascon_top__DOT__xor_tree__100__unnamedblk3__DOT__i;
        IData/*31:0*/ __Vfunc_ascon_top__DOT__xor_tree__100__level;
        IData/*31:0*/ __Vfunc_ascon_top__DOT__xor_tree__101__unnamedblk3__DOT__i;
        IData/*31:0*/ __Vfunc_ascon_top__DOT__xor_tree__101__level;
        IData/*31:0*/ __Vfunc_ascon_top__DOT__xor_tree__102__unnamedblk3__DOT__i;
        IData/*31:0*/ __Vfunc_ascon_top__DOT__xor_tree__103__unnamedblk3__DOT__i;
        IData/*31:0*/ __Vfunc_ascon_top__DOT__xor_tree__104__unnamedblk3__DOT__i;
        IData/*31:0*/ __Vfunc_ascon_top__DOT__xor_tree__105__unnamedblk3__DOT__i;
        IData/*31:0*/ __Vfunc_ascon_top__DOT__xor_tree__106__unnamedblk3__DOT__i;
        IData/*31:0*/ __Vfunc_ascon_top__DOT__xor_tree__107__unnamedblk3__DOT__i;
        IData/*31:0*/ __Vfunc_ascon_top__DOT__xor_tree__108__unnamedblk3__DOT__i;
        IData/*31:0*/ __Vfunc_ascon_top__DOT__xor_tree__109__unnamedblk3__DOT__i;
        VlWide<4>/*127:0*/ __Vfunc_ascon_top__DOT__reverse_bytes__110__Vfuncout;
        VlWide<4>/*127:0*/ __Vfunc_ascon_top__DOT__reverse_bytes__110__x;
        VlWide<4>/*127:0*/ __Vfunc_ascon_top__DOT__reverse_bytes__110__y;
        VlWide<4>/*127:0*/ __Vfunc_ascon_top__DOT__reverse_bytes__111__Vfuncout;
        VlWide<4>/*127:0*/ __Vfunc_ascon_top__DOT__reverse_bytes__111__x;
        VlWide<4>/*127:0*/ __Vfunc_ascon_top__DOT__reverse_bytes__111__y;
        IData/*31:0*/ __VactIterCount;
        VL_IN64(key1,63,0);
        VL_IN64(key2,63,0);
        VL_IN64(nonce1,63,0);
        VL_IN64(nonce2,63,0);
        VL_IN64(initialVector,63,0);
        VL_OUT64(tag1,63,0);
        VL_OUT64(tag2,63,0);
        VL_OUT64(debug_state_0,63,0);
        VL_OUT64(debug_state_1,63,0);
        VL_OUT64(debug_state_2,63,0);
        VL_OUT64(debug_state_3,63,0);
        VL_OUT64(debug_state_4,63,0);
    };
    struct {
        VL_OUT64(debug_round_state_0,63,0);
        VL_OUT64(debug_round_state_1,63,0);
        VL_OUT64(debug_round_state_2,63,0);
        VL_OUT64(debug_round_state_3,63,0);
        VL_OUT64(debug_round_state_4,63,0);
        VL_OUT64(debug_linear_diffusion_state3,63,0);
        VL_OUT64(debug_linear_diffusion_state4,63,0);
        QData/*63:0*/ ascon_top__DOT__state_reg__DOT____Vlvbound_hf68ebc64__1;
        QData/*63:0*/ ascon_top__DOT__state_reg__DOT____Vlvbound_hf68ebc64__2;
        QData/*63:0*/ ascon_top__DOT__state_reg__DOT____Vlvbound_hf68ebc64__3;
        QData/*63:0*/ ascon_top__DOT__state_reg__DOT____Vlvbound_hf68ebc64__4;
        QData/*63:0*/ ascon_top__DOT__key1_reg__DOT__reg_q;
        QData/*63:0*/ ascon_top__DOT__key2_reg__DOT__reg_q;
        QData/*63:0*/ ascon_top__DOT__sipo_reg_x0_debug__DOT__state;
        QData/*63:0*/ ascon_top__DOT__sipo_reg_x0_debug__DOT__next_state;
        QData/*63:0*/ ascon_top__DOT__sipo_reg_x1_debug__DOT__state;
        QData/*63:0*/ ascon_top__DOT__sipo_reg_x1_debug__DOT__next_state;
        QData/*63:0*/ ascon_top__DOT__sipo_reg_x2_debug__DOT__state;
        QData/*63:0*/ ascon_top__DOT__sipo_reg_x2_debug__DOT__next_state;
        QData/*63:0*/ ascon_top__DOT__sipo_reg_x3_debug__DOT__state;
        QData/*63:0*/ ascon_top__DOT__sipo_reg_x3_debug__DOT__next_state;
        QData/*63:0*/ ascon_top__DOT__sipo_reg_x4_debug__DOT__state;
        QData/*63:0*/ ascon_top__DOT__sipo_reg_x4_debug__DOT__next_state;
        QData/*63:0*/ __Vfunc_ascon_top__DOT__rotr64__112__Vfuncout;
        QData/*63:0*/ __Vfunc_ascon_top__DOT__rotr64__112__x;
        QData/*63:0*/ __Vfunc_ascon_top__DOT__rotr64__113__Vfuncout;
        QData/*63:0*/ __Vfunc_ascon_top__DOT__rotr64__113__x;
        QData/*63:0*/ __Vfunc_ascon_top__DOT__rotr64__114__Vfuncout;
        QData/*63:0*/ __Vfunc_ascon_top__DOT__rotr64__114__x;
        QData/*63:0*/ __Vfunc_ascon_top__DOT__rotr64__115__Vfuncout;
        QData/*63:0*/ __Vfunc_ascon_top__DOT__rotr64__115__x;
        QData/*63:0*/ __Vfunc_ascon_top__DOT__rotr64__116__Vfuncout;
        QData/*63:0*/ __Vfunc_ascon_top__DOT__rotr64__116__x;
        QData/*63:0*/ __Vfunc_ascon_top__DOT__rotr64__117__Vfuncout;
        QData/*63:0*/ __Vfunc_ascon_top__DOT__rotr64__117__x;
        QData/*63:0*/ __Vfunc_ascon_top__DOT__rotr64__118__Vfuncout;
        QData/*63:0*/ __Vfunc_ascon_top__DOT__rotr64__118__x;
        QData/*63:0*/ __Vfunc_ascon_top__DOT__rotr64__119__Vfuncout;
        QData/*63:0*/ __Vfunc_ascon_top__DOT__rotr64__119__x;
        QData/*63:0*/ __Vfunc_ascon_top__DOT__rotr64__120__Vfuncout;
        QData/*63:0*/ __Vfunc_ascon_top__DOT__rotr64__120__x;
        QData/*63:0*/ __Vfunc_ascon_top__DOT__rotr64__121__Vfuncout;
        QData/*63:0*/ __Vfunc_ascon_top__DOT__rotr64__121__x;
        VlUnpacked<IData/*21:0*/, 3> ascon_top__DOT__rc_block;
        VlUnpacked<VlWide<4>/*109:0*/, 3> ascon_top__DOT__affine_layer_in;
        VlUnpacked<VlWide<4>/*109:0*/, 3> ascon_top__DOT__affine_layer_out;
        VlUnpacked<SData/*14:0*/, 22> ascon_top__DOT__next_sbox_input;
        VlUnpacked<SData/*14:0*/, 22> ascon_top__DOT__sbox_input;
        VlUnpacked<SData/*14:0*/, 22> ascon_top__DOT__sbox_output;
        VlUnpacked<SData/*14:0*/, 22> ascon_top__DOT__sbox_output_unmasked;
        VlUnpacked<SData/*14:0*/, 22> ascon_top__DOT__mux_sbox_out;
        VlUnpacked<VlWide<4>/*109:0*/, 3> ascon_top__DOT__affine_layer2nd_in;
        VlUnpacked<VlWide<4>/*109:0*/, 3> ascon_top__DOT__affine_layer2nd_out;
        VlUnpacked<QData/*63:0*/, 5> ascon_top__DOT__state_reg_in_absorb;
        VlUnpacked<QData/*63:0*/, 5> ascon_top__DOT__linear_diffusion_debug;
        VlUnpacked<QData/*63:0*/, 5> ascon_top__DOT__state_reg__DOT__state;
        VlUnpacked<QData/*63:0*/, 5> ascon_top__DOT__state_reg__DOT__next_state;
        VlUnpacked<CData/*2:0*/, 3> __Vfunc_ascon_top__DOT__xor_tree__0__stage;
        VlUnpacked<CData/*2:0*/, 3> __Vfunc_ascon_top__DOT__xor_tree__1__stage;
        VlUnpacked<CData/*2:0*/, 3> __Vfunc_ascon_top__DOT__xor_tree__2__stage;
        VlUnpacked<CData/*2:0*/, 3> __Vfunc_ascon_top__DOT__xor_tree__3__stage;
        VlUnpacked<CData/*2:0*/, 3> __Vfunc_ascon_top__DOT__xor_tree__4__stage;
        VlUnpacked<CData/*2:0*/, 3> __Vfunc_ascon_top__DOT__xor_tree__5__stage;
        VlUnpacked<CData/*2:0*/, 3> __Vfunc_ascon_top__DOT__xor_tree__6__stage;
    };
    struct {
        VlUnpacked<CData/*2:0*/, 3> __Vfunc_ascon_top__DOT__xor_tree__7__stage;
        VlUnpacked<CData/*2:0*/, 3> __Vfunc_ascon_top__DOT__xor_tree__8__stage;
        VlUnpacked<CData/*2:0*/, 3> __Vfunc_ascon_top__DOT__xor_tree__9__stage;
        VlUnpacked<CData/*2:0*/, 3> __Vfunc_ascon_top__DOT__xor_tree__10__stage;
        VlUnpacked<CData/*2:0*/, 3> __Vfunc_ascon_top__DOT__xor_tree__11__stage;
        VlUnpacked<CData/*2:0*/, 3> __Vfunc_ascon_top__DOT__xor_tree__12__stage;
        VlUnpacked<CData/*2:0*/, 3> __Vfunc_ascon_top__DOT__xor_tree__13__stage;
        VlUnpacked<CData/*2:0*/, 3> __Vfunc_ascon_top__DOT__xor_tree__14__stage;
        VlUnpacked<CData/*2:0*/, 3> __Vfunc_ascon_top__DOT__xor_tree__15__stage;
        VlUnpacked<CData/*2:0*/, 3> __Vfunc_ascon_top__DOT__xor_tree__16__stage;
        VlUnpacked<CData/*2:0*/, 3> __Vfunc_ascon_top__DOT__xor_tree__17__stage;
        VlUnpacked<CData/*2:0*/, 3> __Vfunc_ascon_top__DOT__xor_tree__18__stage;
        VlUnpacked<CData/*2:0*/, 3> __Vfunc_ascon_top__DOT__xor_tree__19__stage;
        VlUnpacked<CData/*2:0*/, 3> __Vfunc_ascon_top__DOT__xor_tree__20__stage;
        VlUnpacked<CData/*2:0*/, 3> __Vfunc_ascon_top__DOT__xor_tree__21__stage;
        VlUnpacked<CData/*2:0*/, 3> __Vfunc_ascon_top__DOT__xor_tree__22__stage;
        VlUnpacked<CData/*2:0*/, 3> __Vfunc_ascon_top__DOT__xor_tree__23__stage;
        VlUnpacked<CData/*2:0*/, 3> __Vfunc_ascon_top__DOT__xor_tree__24__stage;
        VlUnpacked<CData/*2:0*/, 3> __Vfunc_ascon_top__DOT__xor_tree__25__stage;
        VlUnpacked<CData/*2:0*/, 3> __Vfunc_ascon_top__DOT__xor_tree__26__stage;
        VlUnpacked<CData/*2:0*/, 3> __Vfunc_ascon_top__DOT__xor_tree__27__stage;
        VlUnpacked<CData/*2:0*/, 3> __Vfunc_ascon_top__DOT__xor_tree__28__stage;
        VlUnpacked<CData/*2:0*/, 3> __Vfunc_ascon_top__DOT__xor_tree__29__stage;
        VlUnpacked<CData/*2:0*/, 3> __Vfunc_ascon_top__DOT__xor_tree__30__stage;
        VlUnpacked<CData/*2:0*/, 3> __Vfunc_ascon_top__DOT__xor_tree__31__stage;
        VlUnpacked<CData/*2:0*/, 3> __Vfunc_ascon_top__DOT__xor_tree__32__stage;
        VlUnpacked<CData/*2:0*/, 3> __Vfunc_ascon_top__DOT__xor_tree__33__stage;
        VlUnpacked<CData/*2:0*/, 3> __Vfunc_ascon_top__DOT__xor_tree__34__stage;
        VlUnpacked<CData/*2:0*/, 3> __Vfunc_ascon_top__DOT__xor_tree__35__stage;
        VlUnpacked<CData/*2:0*/, 3> __Vfunc_ascon_top__DOT__xor_tree__36__stage;
        VlUnpacked<CData/*2:0*/, 3> __Vfunc_ascon_top__DOT__xor_tree__37__stage;
        VlUnpacked<CData/*2:0*/, 3> __Vfunc_ascon_top__DOT__xor_tree__38__stage;
        VlUnpacked<CData/*2:0*/, 3> __Vfunc_ascon_top__DOT__xor_tree__39__stage;
        VlUnpacked<CData/*2:0*/, 3> __Vfunc_ascon_top__DOT__xor_tree__40__stage;
        VlUnpacked<CData/*2:0*/, 3> __Vfunc_ascon_top__DOT__xor_tree__41__stage;
        VlUnpacked<CData/*2:0*/, 3> __Vfunc_ascon_top__DOT__xor_tree__42__stage;
        VlUnpacked<CData/*2:0*/, 3> __Vfunc_ascon_top__DOT__xor_tree__43__stage;
        VlUnpacked<CData/*2:0*/, 3> __Vfunc_ascon_top__DOT__xor_tree__44__stage;
        VlUnpacked<CData/*2:0*/, 3> __Vfunc_ascon_top__DOT__xor_tree__45__stage;
        VlUnpacked<CData/*2:0*/, 3> __Vfunc_ascon_top__DOT__xor_tree__46__stage;
        VlUnpacked<CData/*2:0*/, 3> __Vfunc_ascon_top__DOT__xor_tree__47__stage;
        VlUnpacked<CData/*2:0*/, 3> __Vfunc_ascon_top__DOT__xor_tree__48__stage;
        VlUnpacked<CData/*2:0*/, 3> __Vfunc_ascon_top__DOT__xor_tree__49__stage;
        VlUnpacked<CData/*2:0*/, 3> __Vfunc_ascon_top__DOT__xor_tree__50__stage;
        VlUnpacked<CData/*2:0*/, 3> __Vfunc_ascon_top__DOT__xor_tree__51__stage;
        VlUnpacked<CData/*2:0*/, 3> __Vfunc_ascon_top__DOT__xor_tree__52__stage;
        VlUnpacked<CData/*2:0*/, 3> __Vfunc_ascon_top__DOT__xor_tree__53__stage;
        VlUnpacked<CData/*2:0*/, 3> __Vfunc_ascon_top__DOT__xor_tree__54__stage;
        VlUnpacked<CData/*2:0*/, 3> __Vfunc_ascon_top__DOT__xor_tree__55__stage;
        VlUnpacked<CData/*2:0*/, 3> __Vfunc_ascon_top__DOT__xor_tree__56__stage;
        VlUnpacked<CData/*2:0*/, 3> __Vfunc_ascon_top__DOT__xor_tree__57__stage;
        VlUnpacked<CData/*2:0*/, 3> __Vfunc_ascon_top__DOT__xor_tree__58__stage;
        VlUnpacked<CData/*2:0*/, 3> __Vfunc_ascon_top__DOT__xor_tree__59__stage;
        VlUnpacked<CData/*2:0*/, 3> __Vfunc_ascon_top__DOT__xor_tree__60__stage;
        VlUnpacked<CData/*2:0*/, 3> __Vfunc_ascon_top__DOT__xor_tree__61__stage;
        VlUnpacked<CData/*2:0*/, 3> __Vfunc_ascon_top__DOT__xor_tree__62__stage;
        VlUnpacked<CData/*2:0*/, 3> __Vfunc_ascon_top__DOT__xor_tree__63__stage;
        VlUnpacked<CData/*2:0*/, 3> __Vfunc_ascon_top__DOT__xor_tree__64__stage;
        VlUnpacked<CData/*2:0*/, 3> __Vfunc_ascon_top__DOT__xor_tree__65__stage;
        VlUnpacked<CData/*2:0*/, 3> __Vfunc_ascon_top__DOT__xor_tree__66__stage;
        VlUnpacked<CData/*2:0*/, 3> __Vfunc_ascon_top__DOT__xor_tree__67__stage;
        VlUnpacked<CData/*2:0*/, 3> __Vfunc_ascon_top__DOT__xor_tree__68__stage;
        VlUnpacked<CData/*2:0*/, 3> __Vfunc_ascon_top__DOT__xor_tree__69__stage;
        VlUnpacked<CData/*2:0*/, 3> __Vfunc_ascon_top__DOT__xor_tree__70__stage;
    };
    struct {
        VlUnpacked<CData/*2:0*/, 3> __Vfunc_ascon_top__DOT__xor_tree__71__stage;
        VlUnpacked<CData/*2:0*/, 3> __Vfunc_ascon_top__DOT__xor_tree__72__stage;
        VlUnpacked<CData/*2:0*/, 3> __Vfunc_ascon_top__DOT__xor_tree__73__stage;
        VlUnpacked<CData/*2:0*/, 3> __Vfunc_ascon_top__DOT__xor_tree__74__stage;
        VlUnpacked<CData/*2:0*/, 3> __Vfunc_ascon_top__DOT__xor_tree__75__stage;
        VlUnpacked<CData/*2:0*/, 3> __Vfunc_ascon_top__DOT__xor_tree__76__stage;
        VlUnpacked<CData/*2:0*/, 3> __Vfunc_ascon_top__DOT__xor_tree__77__stage;
        VlUnpacked<CData/*2:0*/, 3> __Vfunc_ascon_top__DOT__xor_tree__78__stage;
        VlUnpacked<CData/*2:0*/, 3> __Vfunc_ascon_top__DOT__xor_tree__79__stage;
        VlUnpacked<CData/*2:0*/, 3> __Vfunc_ascon_top__DOT__xor_tree__80__stage;
        VlUnpacked<CData/*2:0*/, 3> __Vfunc_ascon_top__DOT__xor_tree__81__stage;
        VlUnpacked<CData/*2:0*/, 3> __Vfunc_ascon_top__DOT__xor_tree__82__stage;
        VlUnpacked<CData/*2:0*/, 3> __Vfunc_ascon_top__DOT__xor_tree__83__stage;
        VlUnpacked<CData/*2:0*/, 3> __Vfunc_ascon_top__DOT__xor_tree__84__stage;
        VlUnpacked<CData/*2:0*/, 3> __Vfunc_ascon_top__DOT__xor_tree__85__stage;
        VlUnpacked<CData/*2:0*/, 3> __Vfunc_ascon_top__DOT__xor_tree__86__stage;
        VlUnpacked<CData/*2:0*/, 3> __Vfunc_ascon_top__DOT__xor_tree__87__stage;
        VlUnpacked<CData/*2:0*/, 3> __Vfunc_ascon_top__DOT__xor_tree__88__stage;
        VlUnpacked<CData/*2:0*/, 3> __Vfunc_ascon_top__DOT__xor_tree__89__stage;
        VlUnpacked<CData/*2:0*/, 3> __Vfunc_ascon_top__DOT__xor_tree__90__stage;
        VlUnpacked<CData/*2:0*/, 3> __Vfunc_ascon_top__DOT__xor_tree__91__stage;
        VlUnpacked<CData/*2:0*/, 3> __Vfunc_ascon_top__DOT__xor_tree__92__stage;
        VlUnpacked<CData/*2:0*/, 3> __Vfunc_ascon_top__DOT__xor_tree__93__stage;
        VlUnpacked<CData/*2:0*/, 3> __Vfunc_ascon_top__DOT__xor_tree__94__stage;
        VlUnpacked<CData/*2:0*/, 3> __Vfunc_ascon_top__DOT__xor_tree__95__stage;
        VlUnpacked<CData/*2:0*/, 3> __Vfunc_ascon_top__DOT__xor_tree__96__stage;
        VlUnpacked<CData/*2:0*/, 3> __Vfunc_ascon_top__DOT__xor_tree__97__stage;
        VlUnpacked<CData/*2:0*/, 3> __Vfunc_ascon_top__DOT__xor_tree__98__stage;
        VlUnpacked<CData/*2:0*/, 3> __Vfunc_ascon_top__DOT__xor_tree__99__stage;
        VlUnpacked<CData/*2:0*/, 3> __Vfunc_ascon_top__DOT__xor_tree__100__stage;
        VlUnpacked<CData/*2:0*/, 3> __Vfunc_ascon_top__DOT__xor_tree__101__stage;
        VlUnpacked<CData/*2:0*/, 3> __Vfunc_ascon_top__DOT__xor_tree__102__stage;
        VlUnpacked<CData/*2:0*/, 3> __Vfunc_ascon_top__DOT__xor_tree__103__stage;
        VlUnpacked<CData/*2:0*/, 3> __Vfunc_ascon_top__DOT__xor_tree__104__stage;
        VlUnpacked<CData/*2:0*/, 3> __Vfunc_ascon_top__DOT__xor_tree__105__stage;
        VlUnpacked<CData/*2:0*/, 3> __Vfunc_ascon_top__DOT__xor_tree__106__stage;
        VlUnpacked<CData/*2:0*/, 3> __Vfunc_ascon_top__DOT__xor_tree__107__stage;
        VlUnpacked<CData/*2:0*/, 3> __Vfunc_ascon_top__DOT__xor_tree__108__stage;
        VlUnpacked<CData/*2:0*/, 3> __Vfunc_ascon_top__DOT__xor_tree__109__stage;
        VlUnpacked<CData/*0:0*/, 5> __Vm_traceActivity;
    };
    VlTriggerVec<1> __VstlTriggered;
    VlTriggerVec<1> __VicoTriggered;
    VlTriggerVec<2> __VactTriggered;
    VlTriggerVec<2> __VnbaTriggered;

    // INTERNAL VARIABLES
    Vascon_top__Syms* const vlSymsp;

    // PARAMETERS
    static constexpr VlUnpacked<IData/*31:0*/, 5> ascon_top__DOT__rotations_a = {{
        0x00000013U, 0x0000003dU, 0x00000001U, 0x0000000aU,
        0x00000007U
    }};
    static constexpr VlUnpacked<IData/*31:0*/, 5> ascon_top__DOT__rotations_b = {{
        0x0000001cU, 0x00000027U, 0x00000006U, 0x00000011U,
        0x00000029U
    }};

    // CONSTRUCTORS
    Vascon_top___024root(Vascon_top__Syms* symsp, const char* v__name);
    ~Vascon_top___024root();
    VL_UNCOPYABLE(Vascon_top___024root);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
};


#endif  // guard
