// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See Vascon_top.h for the primary calling header

#ifndef VERILATED_VASCON_TOP___024ROOT_H_
#define VERILATED_VASCON_TOP___024ROOT_H_  // guard

#include "verilated.h"


class Vascon_top__Syms;

class alignas(VL_CACHE_LINE_BYTES) Vascon_top___024root final : public VerilatedModule {
  public:

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        VL_IN8(clk,0,0);
        VL_IN8(reset_n,0,0);
        VL_IN8(start,0,0);
        VL_IN8(key_valid,0,0);
        VL_IN8(valid_data_in,0,0);
        VL_IN8(last_block,0,0);
        VL_IN8(valid_bytes,4,0);
        VL_IN8(EOT,0,0);
        VL_OUT8(ciphertext_valid,0,0);
        VL_OUT8(done,0,0);
        VL_OUT8(ready_tag,0,0);
        VL_OUT8(ready_for_data,0,0);
        VL_OUT8(debug_extra_padding_ff,0,0);
        VL_OUT8(debug_bitcounter,3,0);
        VL_OUT8(debug_roundcounter,3,0);
        VL_OUT8(debug_state,4,0);
        CData/*0:0*/ ascon_top__DOT__shift_en;
        CData/*0:0*/ ascon_top__DOT__shift_type;
        CData/*0:0*/ ascon_top__DOT__write_en;
        CData/*0:0*/ ascon_top__DOT__last_cycle;
        CData/*0:0*/ ascon_top__DOT__reg_key1_load;
        CData/*0:0*/ ascon_top__DOT__reg_key2_load;
        CData/*0:0*/ ascon_top__DOT__sel_mux_linear_diffusion_out_x3;
        CData/*0:0*/ ascon_top__DOT__sel_mux_linear_diffusion_out_x4;
        CData/*0:0*/ ascon_top__DOT__sel_init_load;
        CData/*0:0*/ ascon_top__DOT__sel_masked_round;
        CData/*0:0*/ ascon_top__DOT__sel_padding;
        CData/*0:0*/ ascon_top__DOT__sel_xor_signal;
        CData/*0:0*/ ascon_top__DOT__sel_absorb_data;
        CData/*0:0*/ ascon_top__DOT__extra_padding;
        CData/*0:0*/ ascon_top__DOT__shift_enable_sipo;
        CData/*0:0*/ ascon_top__DOT__last_cycle_sipo;
        CData/*3:0*/ ascon_top__DOT__round_counter;
        CData/*3:0*/ ascon_top__DOT__bit_counter;
        CData/*5:0*/ ascon_top__DOT____Vcellinp__sipo_reg_x2_debug__in_shifted_1bit;
        CData/*0:0*/ ascon_top__DOT____Vlvbound_hcf72403f__0;
        CData/*0:0*/ ascon_top__DOT____Vlvbound_h95e776b1__0;
        CData/*0:0*/ ascon_top__DOT____Vlvbound_h63babb1e__0;
        CData/*0:0*/ ascon_top__DOT____Vlvbound_h1ea7c5e7__0;
        CData/*5:0*/ ascon_top__DOT____VdfgRegularize_h0932e10f_3_1;
        CData/*5:0*/ ascon_top__DOT____VdfgRegularize_h0932e10f_3_3;
        CData/*5:0*/ ascon_top__DOT____VdfgRegularize_h0932e10f_3_5;
        CData/*5:0*/ ascon_top__DOT____VdfgRegularize_h0932e10f_3_6;
        CData/*5:0*/ ascon_top__DOT____VdfgRegularize_h0932e10f_3_8;
        CData/*5:0*/ ascon_top__DOT____VdfgRegularize_h0932e10f_3_9;
        CData/*5:0*/ ascon_top__DOT____VdfgRegularize_h0932e10f_3_11;
        CData/*5:0*/ ascon_top__DOT____VdfgRegularize_h0932e10f_3_12;
        CData/*5:0*/ ascon_top__DOT____VdfgRegularize_h0932e10f_3_14;
        CData/*5:0*/ ascon_top__DOT____VdfgRegularize_h0932e10f_3_15;
        CData/*5:0*/ ascon_top__DOT____VdfgRegularize_h0932e10f_3_17;
        CData/*5:0*/ ascon_top__DOT____VdfgRegularize_h0932e10f_3_18;
        CData/*5:0*/ ascon_top__DOT____VdfgRegularize_h0932e10f_3_20;
        CData/*5:0*/ ascon_top__DOT____VdfgRegularize_h0932e10f_3_21;
        CData/*5:0*/ ascon_top__DOT____VdfgRegularize_h0932e10f_3_23;
        CData/*5:0*/ ascon_top__DOT____VdfgRegularize_h0932e10f_3_24;
        CData/*5:0*/ ascon_top__DOT____VdfgRegularize_h0932e10f_3_26;
        CData/*5:0*/ ascon_top__DOT____VdfgRegularize_h0932e10f_3_27;
        CData/*5:0*/ ascon_top__DOT____VdfgRegularize_h0932e10f_3_29;
        CData/*5:0*/ ascon_top__DOT____VdfgRegularize_h0932e10f_3_30;
        CData/*5:0*/ ascon_top__DOT____VdfgRegularize_h0932e10f_3_32;
        CData/*5:0*/ ascon_top__DOT____VdfgRegularize_h0932e10f_3_33;
        CData/*4:0*/ ascon_top__DOT__mealy_fsm__DOT__current_state;
        CData/*4:0*/ ascon_top__DOT__mealy_fsm__DOT__next_state;
        CData/*3:0*/ ascon_top__DOT__mealy_fsm__DOT__number_bits;
    };
    struct {
        CData/*3:0*/ ascon_top__DOT__mealy_fsm__DOT__number_round;
        CData/*0:0*/ ascon_top__DOT__mealy_fsm__DOT__last_block_process;
        CData/*0:0*/ ascon_top__DOT__mealy_fsm__DOT__last_block_process_ff;
        CData/*0:0*/ ascon_top__DOT__mealy_fsm__DOT__last_block_process_load;
        CData/*0:0*/ ascon_top__DOT__mealy_fsm__DOT__extra_padding_load;
        CData/*0:0*/ ascon_top__DOT__mealy_fsm__DOT__round_counter_enable;
        CData/*0:0*/ ascon_top__DOT__mealy_fsm__DOT__rst_counter_round;
        CData/*0:0*/ ascon_top__DOT__gen_unsupported__DOT__gen_sbox__BRA__0__KET____DOT__u_sbox__DOT____Vlvbound_h50f15c30__0;
        CData/*0:0*/ ascon_top__DOT__gen_unsupported__DOT__gen_sbox__BRA__0__KET____DOT__u_sbox__DOT____Vlvbound_h6042fdd8__0;
        CData/*0:0*/ ascon_top__DOT__gen_unsupported__DOT__gen_sbox__BRA__0__KET____DOT__u_sbox__DOT____Vlvbound_h50f15c30__1;
        CData/*0:0*/ ascon_top__DOT__gen_unsupported__DOT__gen_sbox__BRA__0__KET____DOT__u_sbox__DOT____Vlvbound_h0c5d65aa__0;
        CData/*0:0*/ ascon_top__DOT__gen_unsupported__DOT__gen_sbox__BRA__0__KET____DOT__u_sbox__DOT____Vlvbound_h6d5115e6__0;
        CData/*0:0*/ ascon_top__DOT__gen_unsupported__DOT__gen_sbox__BRA__0__KET____DOT__u_sbox__DOT____Vlvbound_h520efa72__0;
        CData/*0:0*/ ascon_top__DOT__gen_unsupported__DOT__gen_sbox__BRA__0__KET____DOT__u_sbox__DOT____Vlvbound_h63babb1e__0;
        CData/*0:0*/ ascon_top__DOT__gen_unsupported__DOT__gen_sbox__BRA__0__KET____DOT__u_sbox__DOT____Vlvbound_hf81e60fa__0;
        CData/*0:0*/ ascon_top__DOT__gen_unsupported__DOT__gen_sbox__BRA__0__KET____DOT__u_sbox__DOT____Vlvbound_h268865b4__0;
        CData/*0:0*/ ascon_top__DOT__gen_unsupported__DOT__gen_sbox__BRA__1__KET____DOT__u_sbox__DOT____Vlvbound_h50f15c30__0;
        CData/*0:0*/ ascon_top__DOT__gen_unsupported__DOT__gen_sbox__BRA__1__KET____DOT__u_sbox__DOT____Vlvbound_h6042fdd8__0;
        CData/*0:0*/ ascon_top__DOT__gen_unsupported__DOT__gen_sbox__BRA__1__KET____DOT__u_sbox__DOT____Vlvbound_h50f15c30__1;
        CData/*0:0*/ ascon_top__DOT__gen_unsupported__DOT__gen_sbox__BRA__1__KET____DOT__u_sbox__DOT____Vlvbound_h0c5d65aa__0;
        CData/*0:0*/ ascon_top__DOT__gen_unsupported__DOT__gen_sbox__BRA__1__KET____DOT__u_sbox__DOT____Vlvbound_h6d5115e6__0;
        CData/*0:0*/ ascon_top__DOT__gen_unsupported__DOT__gen_sbox__BRA__1__KET____DOT__u_sbox__DOT____Vlvbound_h520efa72__0;
        CData/*0:0*/ ascon_top__DOT__gen_unsupported__DOT__gen_sbox__BRA__1__KET____DOT__u_sbox__DOT____Vlvbound_h63babb1e__0;
        CData/*0:0*/ ascon_top__DOT__gen_unsupported__DOT__gen_sbox__BRA__1__KET____DOT__u_sbox__DOT____Vlvbound_hf81e60fa__0;
        CData/*0:0*/ ascon_top__DOT__gen_unsupported__DOT__gen_sbox__BRA__1__KET____DOT__u_sbox__DOT____Vlvbound_h268865b4__0;
        CData/*0:0*/ ascon_top__DOT__gen_unsupported__DOT__gen_sbox__BRA__2__KET____DOT__u_sbox__DOT____Vlvbound_h50f15c30__0;
        CData/*0:0*/ ascon_top__DOT__gen_unsupported__DOT__gen_sbox__BRA__2__KET____DOT__u_sbox__DOT____Vlvbound_h6042fdd8__0;
        CData/*0:0*/ ascon_top__DOT__gen_unsupported__DOT__gen_sbox__BRA__2__KET____DOT__u_sbox__DOT____Vlvbound_h50f15c30__1;
        CData/*0:0*/ ascon_top__DOT__gen_unsupported__DOT__gen_sbox__BRA__2__KET____DOT__u_sbox__DOT____Vlvbound_h0c5d65aa__0;
        CData/*0:0*/ ascon_top__DOT__gen_unsupported__DOT__gen_sbox__BRA__2__KET____DOT__u_sbox__DOT____Vlvbound_h6d5115e6__0;
        CData/*0:0*/ ascon_top__DOT__gen_unsupported__DOT__gen_sbox__BRA__2__KET____DOT__u_sbox__DOT____Vlvbound_h520efa72__0;
        CData/*0:0*/ ascon_top__DOT__gen_unsupported__DOT__gen_sbox__BRA__2__KET____DOT__u_sbox__DOT____Vlvbound_h63babb1e__0;
        CData/*0:0*/ ascon_top__DOT__gen_unsupported__DOT__gen_sbox__BRA__2__KET____DOT__u_sbox__DOT____Vlvbound_hf81e60fa__0;
        CData/*0:0*/ ascon_top__DOT__gen_unsupported__DOT__gen_sbox__BRA__2__KET____DOT__u_sbox__DOT____Vlvbound_h268865b4__0;
        CData/*0:0*/ ascon_top__DOT__gen_unsupported__DOT__gen_sbox__BRA__3__KET____DOT__u_sbox__DOT____Vlvbound_h50f15c30__0;
        CData/*0:0*/ ascon_top__DOT__gen_unsupported__DOT__gen_sbox__BRA__3__KET____DOT__u_sbox__DOT____Vlvbound_h6042fdd8__0;
        CData/*0:0*/ ascon_top__DOT__gen_unsupported__DOT__gen_sbox__BRA__3__KET____DOT__u_sbox__DOT____Vlvbound_h50f15c30__1;
        CData/*0:0*/ ascon_top__DOT__gen_unsupported__DOT__gen_sbox__BRA__3__KET____DOT__u_sbox__DOT____Vlvbound_h0c5d65aa__0;
        CData/*0:0*/ ascon_top__DOT__gen_unsupported__DOT__gen_sbox__BRA__3__KET____DOT__u_sbox__DOT____Vlvbound_h6d5115e6__0;
        CData/*0:0*/ ascon_top__DOT__gen_unsupported__DOT__gen_sbox__BRA__3__KET____DOT__u_sbox__DOT____Vlvbound_h520efa72__0;
        CData/*0:0*/ ascon_top__DOT__gen_unsupported__DOT__gen_sbox__BRA__3__KET____DOT__u_sbox__DOT____Vlvbound_h63babb1e__0;
        CData/*0:0*/ ascon_top__DOT__gen_unsupported__DOT__gen_sbox__BRA__3__KET____DOT__u_sbox__DOT____Vlvbound_hf81e60fa__0;
        CData/*0:0*/ ascon_top__DOT__gen_unsupported__DOT__gen_sbox__BRA__3__KET____DOT__u_sbox__DOT____Vlvbound_h268865b4__0;
        CData/*0:0*/ ascon_top__DOT__gen_unsupported__DOT__gen_sbox__BRA__4__KET____DOT__u_sbox__DOT____Vlvbound_h50f15c30__0;
        CData/*0:0*/ ascon_top__DOT__gen_unsupported__DOT__gen_sbox__BRA__4__KET____DOT__u_sbox__DOT____Vlvbound_h6042fdd8__0;
        CData/*0:0*/ ascon_top__DOT__gen_unsupported__DOT__gen_sbox__BRA__4__KET____DOT__u_sbox__DOT____Vlvbound_h50f15c30__1;
        CData/*0:0*/ ascon_top__DOT__gen_unsupported__DOT__gen_sbox__BRA__4__KET____DOT__u_sbox__DOT____Vlvbound_h0c5d65aa__0;
        CData/*0:0*/ ascon_top__DOT__gen_unsupported__DOT__gen_sbox__BRA__4__KET____DOT__u_sbox__DOT____Vlvbound_h6d5115e6__0;
        CData/*0:0*/ ascon_top__DOT__gen_unsupported__DOT__gen_sbox__BRA__4__KET____DOT__u_sbox__DOT____Vlvbound_h520efa72__0;
        CData/*0:0*/ ascon_top__DOT__gen_unsupported__DOT__gen_sbox__BRA__4__KET____DOT__u_sbox__DOT____Vlvbound_h63babb1e__0;
        CData/*0:0*/ ascon_top__DOT__gen_unsupported__DOT__gen_sbox__BRA__4__KET____DOT__u_sbox__DOT____Vlvbound_hf81e60fa__0;
        CData/*0:0*/ ascon_top__DOT__gen_unsupported__DOT__gen_sbox__BRA__4__KET____DOT__u_sbox__DOT____Vlvbound_h268865b4__0;
        CData/*0:0*/ ascon_top__DOT__gen_unsupported__DOT__gen_sbox__BRA__5__KET____DOT__u_sbox__DOT____Vlvbound_h50f15c30__0;
        CData/*0:0*/ ascon_top__DOT__gen_unsupported__DOT__gen_sbox__BRA__5__KET____DOT__u_sbox__DOT____Vlvbound_h6042fdd8__0;
        CData/*0:0*/ ascon_top__DOT__gen_unsupported__DOT__gen_sbox__BRA__5__KET____DOT__u_sbox__DOT____Vlvbound_h50f15c30__1;
        CData/*0:0*/ ascon_top__DOT__gen_unsupported__DOT__gen_sbox__BRA__5__KET____DOT__u_sbox__DOT____Vlvbound_h0c5d65aa__0;
        CData/*0:0*/ ascon_top__DOT__gen_unsupported__DOT__gen_sbox__BRA__5__KET____DOT__u_sbox__DOT____Vlvbound_h6d5115e6__0;
        CData/*0:0*/ ascon_top__DOT__gen_unsupported__DOT__gen_sbox__BRA__5__KET____DOT__u_sbox__DOT____Vlvbound_h520efa72__0;
        CData/*0:0*/ ascon_top__DOT__gen_unsupported__DOT__gen_sbox__BRA__5__KET____DOT__u_sbox__DOT____Vlvbound_h63babb1e__0;
        CData/*0:0*/ ascon_top__DOT__gen_unsupported__DOT__gen_sbox__BRA__5__KET____DOT__u_sbox__DOT____Vlvbound_hf81e60fa__0;
        CData/*0:0*/ ascon_top__DOT__gen_unsupported__DOT__gen_sbox__BRA__5__KET____DOT__u_sbox__DOT____Vlvbound_h268865b4__0;
        CData/*0:0*/ __Vfunc_ascon_top__DOT__xor_tree__27__Vfuncout;
        CData/*0:0*/ __Vfunc_ascon_top__DOT__gen_unsupported__DOT__gen_sbox__BRA__0__KET____DOT__u_sbox__DOT__xor_tree__42__Vfuncout;
        CData/*0:0*/ __Vfunc_ascon_top__DOT__gen_unsupported__DOT__gen_sbox__BRA__1__KET____DOT__u_sbox__DOT__xor_tree__43__Vfuncout;
    };
    struct {
        CData/*0:0*/ __Vfunc_ascon_top__DOT__gen_unsupported__DOT__gen_sbox__BRA__2__KET____DOT__u_sbox__DOT__xor_tree__44__Vfuncout;
        CData/*0:0*/ __Vfunc_ascon_top__DOT__gen_unsupported__DOT__gen_sbox__BRA__3__KET____DOT__u_sbox__DOT__xor_tree__45__Vfuncout;
        CData/*0:0*/ __Vfunc_ascon_top__DOT__gen_unsupported__DOT__gen_sbox__BRA__4__KET____DOT__u_sbox__DOT__xor_tree__46__Vfuncout;
        CData/*0:0*/ __Vfunc_ascon_top__DOT__gen_unsupported__DOT__gen_sbox__BRA__5__KET____DOT__u_sbox__DOT__xor_tree__47__Vfuncout;
        CData/*0:0*/ __VstlFirstIteration;
        CData/*0:0*/ __VicoFirstIteration;
        CData/*0:0*/ __Vtrigprevexpr___TOP__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__reset_n__0;
        CData/*0:0*/ __VactContinue;
        SData/*10:0*/ ascon_top__DOT__recombine__BRA__0__KET____DOT__temp_bits;
        SData/*10:0*/ ascon_top__DOT__recombine__BRA__1__KET____DOT__temp_bits;
        SData/*10:0*/ ascon_top__DOT__recombine__BRA__2__KET____DOT__temp_bits;
        SData/*10:0*/ ascon_top__DOT__recombine__BRA__3__KET____DOT__temp_bits;
        SData/*10:0*/ ascon_top__DOT__recombine__BRA__4__KET____DOT__temp_bits;
        SData/*10:0*/ ascon_top__DOT__recombine__BRA__5__KET____DOT__temp_bits;
        SData/*10:0*/ ascon_top__DOT__recombine__BRA__6__KET____DOT__temp_bits;
        SData/*10:0*/ ascon_top__DOT__recombine__BRA__7__KET____DOT__temp_bits;
        SData/*10:0*/ ascon_top__DOT__recombine__BRA__8__KET____DOT__temp_bits;
        SData/*10:0*/ ascon_top__DOT__recombine__BRA__9__KET____DOT__temp_bits;
        SData/*10:0*/ ascon_top__DOT__recombine__BRA__10__KET____DOT__temp_bits;
        SData/*10:0*/ ascon_top__DOT__recombine__BRA__11__KET____DOT__temp_bits;
        SData/*10:0*/ ascon_top__DOT__recombine__BRA__12__KET____DOT__temp_bits;
        SData/*10:0*/ ascon_top__DOT__recombine__BRA__13__KET____DOT__temp_bits;
        SData/*10:0*/ ascon_top__DOT__recombine__BRA__14__KET____DOT__temp_bits;
        SData/*10:0*/ ascon_top__DOT__recombine__BRA__15__KET____DOT__temp_bits;
        SData/*10:0*/ ascon_top__DOT__recombine__BRA__16__KET____DOT__temp_bits;
        SData/*10:0*/ ascon_top__DOT__recombine__BRA__17__KET____DOT__temp_bits;
        SData/*10:0*/ ascon_top__DOT__recombine__BRA__18__KET____DOT__temp_bits;
        SData/*10:0*/ ascon_top__DOT__recombine__BRA__19__KET____DOT__temp_bits;
        SData/*10:0*/ ascon_top__DOT__recombine__BRA__20__KET____DOT__temp_bits;
        SData/*10:0*/ ascon_top__DOT__recombine__BRA__21__KET____DOT__temp_bits;
        SData/*10:0*/ ascon_top__DOT__recombine__BRA__22__KET____DOT__temp_bits;
        SData/*10:0*/ ascon_top__DOT__recombine__BRA__23__KET____DOT__temp_bits;
        SData/*10:0*/ ascon_top__DOT__recombine__BRA__24__KET____DOT__temp_bits;
        SData/*10:0*/ ascon_top__DOT__recombine__BRA__25__KET____DOT__temp_bits;
        SData/*10:0*/ ascon_top__DOT__recombine__BRA__26__KET____DOT__temp_bits;
        SData/*10:0*/ ascon_top__DOT__recombine__BRA__27__KET____DOT__temp_bits;
        SData/*10:0*/ ascon_top__DOT__recombine__BRA__28__KET____DOT__temp_bits;
        SData/*10:0*/ ascon_top__DOT__recombine__BRA__29__KET____DOT__temp_bits;
        SData/*10:0*/ ascon_top__DOT__gen_unsupported__DOT__gen_sbox__BRA__0__KET____DOT__u_sbox__DOT__unnamedblk1__DOT__unnamedblk3__DOT__unnamedblk4__DOT__xi;
        SData/*10:0*/ ascon_top__DOT__gen_unsupported__DOT__gen_sbox__BRA__0__KET____DOT__u_sbox__DOT__unnamedblk1__DOT__unnamedblk3__DOT__unnamedblk4__DOT__xiprox1;
        SData/*10:0*/ ascon_top__DOT__gen_unsupported__DOT__gen_sbox__BRA__0__KET____DOT__u_sbox__DOT__unnamedblk1__DOT__unnamedblk3__DOT__unnamedblk4__DOT__xiprox2;
        SData/*10:0*/ ascon_top__DOT__gen_unsupported__DOT__gen_sbox__BRA__0__KET____DOT__u_sbox__DOT__unnamedblk1__DOT__unnamedblk3__DOT__unnamedblk4__DOT__not_xiprox1;
        SData/*10:0*/ ascon_top__DOT__gen_unsupported__DOT__gen_sbox__BRA__0__KET____DOT__u_sbox__DOT__unnamedblk10__DOT__unnamedblk11__DOT__unnamedblk12__DOT__temp;
        SData/*10:0*/ ascon_top__DOT__gen_unsupported__DOT__gen_sbox__BRA__1__KET____DOT__u_sbox__DOT__unnamedblk1__DOT__unnamedblk3__DOT__unnamedblk4__DOT__xi;
        SData/*10:0*/ ascon_top__DOT__gen_unsupported__DOT__gen_sbox__BRA__1__KET____DOT__u_sbox__DOT__unnamedblk1__DOT__unnamedblk3__DOT__unnamedblk4__DOT__xiprox1;
        SData/*10:0*/ ascon_top__DOT__gen_unsupported__DOT__gen_sbox__BRA__1__KET____DOT__u_sbox__DOT__unnamedblk1__DOT__unnamedblk3__DOT__unnamedblk4__DOT__xiprox2;
        SData/*10:0*/ ascon_top__DOT__gen_unsupported__DOT__gen_sbox__BRA__1__KET____DOT__u_sbox__DOT__unnamedblk1__DOT__unnamedblk3__DOT__unnamedblk4__DOT__not_xiprox1;
        SData/*10:0*/ ascon_top__DOT__gen_unsupported__DOT__gen_sbox__BRA__1__KET____DOT__u_sbox__DOT__unnamedblk10__DOT__unnamedblk11__DOT__unnamedblk12__DOT__temp;
        SData/*10:0*/ ascon_top__DOT__gen_unsupported__DOT__gen_sbox__BRA__2__KET____DOT__u_sbox__DOT__unnamedblk1__DOT__unnamedblk3__DOT__unnamedblk4__DOT__xi;
        SData/*10:0*/ ascon_top__DOT__gen_unsupported__DOT__gen_sbox__BRA__2__KET____DOT__u_sbox__DOT__unnamedblk1__DOT__unnamedblk3__DOT__unnamedblk4__DOT__xiprox1;
        SData/*10:0*/ ascon_top__DOT__gen_unsupported__DOT__gen_sbox__BRA__2__KET____DOT__u_sbox__DOT__unnamedblk1__DOT__unnamedblk3__DOT__unnamedblk4__DOT__xiprox2;
        SData/*10:0*/ ascon_top__DOT__gen_unsupported__DOT__gen_sbox__BRA__2__KET____DOT__u_sbox__DOT__unnamedblk1__DOT__unnamedblk3__DOT__unnamedblk4__DOT__not_xiprox1;
        SData/*10:0*/ ascon_top__DOT__gen_unsupported__DOT__gen_sbox__BRA__2__KET____DOT__u_sbox__DOT__unnamedblk10__DOT__unnamedblk11__DOT__unnamedblk12__DOT__temp;
        SData/*10:0*/ ascon_top__DOT__gen_unsupported__DOT__gen_sbox__BRA__3__KET____DOT__u_sbox__DOT__unnamedblk1__DOT__unnamedblk3__DOT__unnamedblk4__DOT__xi;
        SData/*10:0*/ ascon_top__DOT__gen_unsupported__DOT__gen_sbox__BRA__3__KET____DOT__u_sbox__DOT__unnamedblk1__DOT__unnamedblk3__DOT__unnamedblk4__DOT__xiprox1;
        SData/*10:0*/ ascon_top__DOT__gen_unsupported__DOT__gen_sbox__BRA__3__KET____DOT__u_sbox__DOT__unnamedblk1__DOT__unnamedblk3__DOT__unnamedblk4__DOT__xiprox2;
        SData/*10:0*/ ascon_top__DOT__gen_unsupported__DOT__gen_sbox__BRA__3__KET____DOT__u_sbox__DOT__unnamedblk1__DOT__unnamedblk3__DOT__unnamedblk4__DOT__not_xiprox1;
        SData/*10:0*/ ascon_top__DOT__gen_unsupported__DOT__gen_sbox__BRA__3__KET____DOT__u_sbox__DOT__unnamedblk10__DOT__unnamedblk11__DOT__unnamedblk12__DOT__temp;
        SData/*10:0*/ ascon_top__DOT__gen_unsupported__DOT__gen_sbox__BRA__4__KET____DOT__u_sbox__DOT__unnamedblk1__DOT__unnamedblk3__DOT__unnamedblk4__DOT__xi;
        SData/*10:0*/ ascon_top__DOT__gen_unsupported__DOT__gen_sbox__BRA__4__KET____DOT__u_sbox__DOT__unnamedblk1__DOT__unnamedblk3__DOT__unnamedblk4__DOT__xiprox1;
        SData/*10:0*/ ascon_top__DOT__gen_unsupported__DOT__gen_sbox__BRA__4__KET____DOT__u_sbox__DOT__unnamedblk1__DOT__unnamedblk3__DOT__unnamedblk4__DOT__xiprox2;
        SData/*10:0*/ ascon_top__DOT__gen_unsupported__DOT__gen_sbox__BRA__4__KET____DOT__u_sbox__DOT__unnamedblk1__DOT__unnamedblk3__DOT__unnamedblk4__DOT__not_xiprox1;
        SData/*10:0*/ ascon_top__DOT__gen_unsupported__DOT__gen_sbox__BRA__4__KET____DOT__u_sbox__DOT__unnamedblk10__DOT__unnamedblk11__DOT__unnamedblk12__DOT__temp;
    };
    struct {
        SData/*10:0*/ ascon_top__DOT__gen_unsupported__DOT__gen_sbox__BRA__5__KET____DOT__u_sbox__DOT__unnamedblk1__DOT__unnamedblk3__DOT__unnamedblk4__DOT__xi;
        SData/*10:0*/ ascon_top__DOT__gen_unsupported__DOT__gen_sbox__BRA__5__KET____DOT__u_sbox__DOT__unnamedblk1__DOT__unnamedblk3__DOT__unnamedblk4__DOT__xiprox1;
        SData/*10:0*/ ascon_top__DOT__gen_unsupported__DOT__gen_sbox__BRA__5__KET____DOT__u_sbox__DOT__unnamedblk1__DOT__unnamedblk3__DOT__unnamedblk4__DOT__xiprox2;
        SData/*10:0*/ ascon_top__DOT__gen_unsupported__DOT__gen_sbox__BRA__5__KET____DOT__u_sbox__DOT__unnamedblk1__DOT__unnamedblk3__DOT__unnamedblk4__DOT__not_xiprox1;
        SData/*10:0*/ ascon_top__DOT__gen_unsupported__DOT__gen_sbox__BRA__5__KET____DOT__u_sbox__DOT__unnamedblk10__DOT__unnamedblk11__DOT__unnamedblk12__DOT__temp;
        SData/*10:0*/ __Vfunc_ascon_top__DOT__gen_unsupported__DOT__gen_sbox__BRA__0__KET____DOT__u_sbox__DOT__xor_tree__42__in;
        SData/*10:0*/ __Vfunc_ascon_top__DOT__gen_unsupported__DOT__gen_sbox__BRA__1__KET____DOT__u_sbox__DOT__xor_tree__43__in;
        SData/*10:0*/ __Vfunc_ascon_top__DOT__gen_unsupported__DOT__gen_sbox__BRA__2__KET____DOT__u_sbox__DOT__xor_tree__44__in;
        SData/*10:0*/ __Vfunc_ascon_top__DOT__gen_unsupported__DOT__gen_sbox__BRA__3__KET____DOT__u_sbox__DOT__xor_tree__45__in;
        SData/*10:0*/ __Vfunc_ascon_top__DOT__gen_unsupported__DOT__gen_sbox__BRA__4__KET____DOT__u_sbox__DOT__xor_tree__46__in;
        SData/*10:0*/ __Vfunc_ascon_top__DOT__gen_unsupported__DOT__gen_sbox__BRA__5__KET____DOT__u_sbox__DOT__xor_tree__47__in;
        VL_INW(data_in,127,0,4);
        VL_INW(random_masks,299,0,10);
        VL_OUTW(ciphertext,127,0,4);
        VlWide<10>/*319:0*/ ascon_top__DOT__state_reg_out;
        VlWide<10>/*319:0*/ ascon_top__DOT__state_reg_in;
        VlWide<10>/*319:0*/ ascon_top__DOT__state_reg_out_shiftdplus1;
        VlWide<10>/*319:0*/ ascon_top__DOT__state_reg_in_shiftdplus1;
        VlWide<11>/*329:0*/ ascon_top__DOT__shares_out;
        IData/*29:0*/ ascon_top__DOT__shares_in;
        IData/*29:0*/ ascon_top__DOT__recombine_shares;
        VlWide<4>/*127:0*/ ascon_top__DOT__data_in_padded;
        VlWide<4>/*127:0*/ ascon_top__DOT__reverse_reg_data_out;
        IData/*31:0*/ ascon_top__DOT__unnamedblk1__DOT__p;
        IData/*31:0*/ ascon_top__DOT__unnamedblk5__DOT__i;
        VlWide<6>/*191:0*/ ascon_top__DOT____VdfgRegularize_h0932e10f_2_0;
        IData/*31:0*/ ascon_top__DOT__state_reg__DOT__unnamedblk3__DOT__i;
        IData/*29:0*/ ascon_top__DOT__share_creator__DOT__temp;
        IData/*31:0*/ ascon_top__DOT__gen_unsupported__DOT__gen_sbox__BRA__0__KET____DOT__u_sbox__DOT__unnamedblk1__DOT__fresh_idx;
        IData/*31:0*/ ascon_top__DOT__gen_unsupported__DOT__gen_sbox__BRA__0__KET____DOT__u_sbox__DOT__unnamedblk1__DOT__unnamedblk3__DOT__unnamedblk4__DOT__unnamedblk5__DOT__j;
        IData/*31:0*/ ascon_top__DOT__gen_unsupported__DOT__gen_sbox__BRA__0__KET____DOT__u_sbox__DOT__unnamedblk1__DOT__unnamedblk3__DOT__unnamedblk4__DOT__unnamedblk5__DOT__unnamedblk6__DOT__k;
        IData/*31:0*/ ascon_top__DOT__gen_unsupported__DOT__gen_sbox__BRA__0__KET____DOT__u_sbox__DOT__unnamedblk7__DOT__i;
        IData/*31:0*/ ascon_top__DOT__gen_unsupported__DOT__gen_sbox__BRA__0__KET____DOT__u_sbox__DOT__unnamedblk10__DOT__i;
        IData/*31:0*/ ascon_top__DOT__gen_unsupported__DOT__gen_sbox__BRA__0__KET____DOT__u_sbox__DOT__unnamedblk10__DOT__unnamedblk11__DOT__j;
        IData/*31:0*/ ascon_top__DOT__gen_unsupported__DOT__gen_sbox__BRA__0__KET____DOT__u_sbox__DOT__unnamedblk10__DOT__unnamedblk11__DOT__unnamedblk12__DOT__unnamedblk13__DOT__k;
        IData/*31:0*/ ascon_top__DOT__gen_unsupported__DOT__gen_sbox__BRA__1__KET____DOT__u_sbox__DOT__unnamedblk1__DOT__fresh_idx;
        IData/*31:0*/ ascon_top__DOT__gen_unsupported__DOT__gen_sbox__BRA__1__KET____DOT__u_sbox__DOT__unnamedblk1__DOT__unnamedblk3__DOT__unnamedblk4__DOT__unnamedblk5__DOT__j;
        IData/*31:0*/ ascon_top__DOT__gen_unsupported__DOT__gen_sbox__BRA__1__KET____DOT__u_sbox__DOT__unnamedblk1__DOT__unnamedblk3__DOT__unnamedblk4__DOT__unnamedblk5__DOT__unnamedblk6__DOT__k;
        IData/*31:0*/ ascon_top__DOT__gen_unsupported__DOT__gen_sbox__BRA__1__KET____DOT__u_sbox__DOT__unnamedblk7__DOT__i;
        IData/*31:0*/ ascon_top__DOT__gen_unsupported__DOT__gen_sbox__BRA__1__KET____DOT__u_sbox__DOT__unnamedblk10__DOT__i;
        IData/*31:0*/ ascon_top__DOT__gen_unsupported__DOT__gen_sbox__BRA__1__KET____DOT__u_sbox__DOT__unnamedblk10__DOT__unnamedblk11__DOT__j;
        IData/*31:0*/ ascon_top__DOT__gen_unsupported__DOT__gen_sbox__BRA__1__KET____DOT__u_sbox__DOT__unnamedblk10__DOT__unnamedblk11__DOT__unnamedblk12__DOT__unnamedblk13__DOT__k;
        IData/*31:0*/ ascon_top__DOT__gen_unsupported__DOT__gen_sbox__BRA__2__KET____DOT__u_sbox__DOT__unnamedblk1__DOT__fresh_idx;
        IData/*31:0*/ ascon_top__DOT__gen_unsupported__DOT__gen_sbox__BRA__2__KET____DOT__u_sbox__DOT__unnamedblk1__DOT__unnamedblk3__DOT__unnamedblk4__DOT__unnamedblk5__DOT__j;
        IData/*31:0*/ ascon_top__DOT__gen_unsupported__DOT__gen_sbox__BRA__2__KET____DOT__u_sbox__DOT__unnamedblk1__DOT__unnamedblk3__DOT__unnamedblk4__DOT__unnamedblk5__DOT__unnamedblk6__DOT__k;
        IData/*31:0*/ ascon_top__DOT__gen_unsupported__DOT__gen_sbox__BRA__2__KET____DOT__u_sbox__DOT__unnamedblk7__DOT__i;
        IData/*31:0*/ ascon_top__DOT__gen_unsupported__DOT__gen_sbox__BRA__2__KET____DOT__u_sbox__DOT__unnamedblk10__DOT__i;
        IData/*31:0*/ ascon_top__DOT__gen_unsupported__DOT__gen_sbox__BRA__2__KET____DOT__u_sbox__DOT__unnamedblk10__DOT__unnamedblk11__DOT__j;
        IData/*31:0*/ ascon_top__DOT__gen_unsupported__DOT__gen_sbox__BRA__2__KET____DOT__u_sbox__DOT__unnamedblk10__DOT__unnamedblk11__DOT__unnamedblk12__DOT__unnamedblk13__DOT__k;
        IData/*31:0*/ ascon_top__DOT__gen_unsupported__DOT__gen_sbox__BRA__3__KET____DOT__u_sbox__DOT__unnamedblk1__DOT__fresh_idx;
        IData/*31:0*/ ascon_top__DOT__gen_unsupported__DOT__gen_sbox__BRA__3__KET____DOT__u_sbox__DOT__unnamedblk1__DOT__unnamedblk3__DOT__unnamedblk4__DOT__unnamedblk5__DOT__j;
        IData/*31:0*/ ascon_top__DOT__gen_unsupported__DOT__gen_sbox__BRA__3__KET____DOT__u_sbox__DOT__unnamedblk1__DOT__unnamedblk3__DOT__unnamedblk4__DOT__unnamedblk5__DOT__unnamedblk6__DOT__k;
        IData/*31:0*/ ascon_top__DOT__gen_unsupported__DOT__gen_sbox__BRA__3__KET____DOT__u_sbox__DOT__unnamedblk7__DOT__i;
        IData/*31:0*/ ascon_top__DOT__gen_unsupported__DOT__gen_sbox__BRA__3__KET____DOT__u_sbox__DOT__unnamedblk10__DOT__i;
        IData/*31:0*/ ascon_top__DOT__gen_unsupported__DOT__gen_sbox__BRA__3__KET____DOT__u_sbox__DOT__unnamedblk10__DOT__unnamedblk11__DOT__j;
        IData/*31:0*/ ascon_top__DOT__gen_unsupported__DOT__gen_sbox__BRA__3__KET____DOT__u_sbox__DOT__unnamedblk10__DOT__unnamedblk11__DOT__unnamedblk12__DOT__unnamedblk13__DOT__k;
        IData/*31:0*/ ascon_top__DOT__gen_unsupported__DOT__gen_sbox__BRA__4__KET____DOT__u_sbox__DOT__unnamedblk1__DOT__fresh_idx;
        IData/*31:0*/ ascon_top__DOT__gen_unsupported__DOT__gen_sbox__BRA__4__KET____DOT__u_sbox__DOT__unnamedblk1__DOT__unnamedblk3__DOT__unnamedblk4__DOT__unnamedblk5__DOT__j;
        IData/*31:0*/ ascon_top__DOT__gen_unsupported__DOT__gen_sbox__BRA__4__KET____DOT__u_sbox__DOT__unnamedblk1__DOT__unnamedblk3__DOT__unnamedblk4__DOT__unnamedblk5__DOT__unnamedblk6__DOT__k;
        IData/*31:0*/ ascon_top__DOT__gen_unsupported__DOT__gen_sbox__BRA__4__KET____DOT__u_sbox__DOT__unnamedblk7__DOT__i;
        IData/*31:0*/ ascon_top__DOT__gen_unsupported__DOT__gen_sbox__BRA__4__KET____DOT__u_sbox__DOT__unnamedblk10__DOT__i;
        IData/*31:0*/ ascon_top__DOT__gen_unsupported__DOT__gen_sbox__BRA__4__KET____DOT__u_sbox__DOT__unnamedblk10__DOT__unnamedblk11__DOT__j;
        IData/*31:0*/ ascon_top__DOT__gen_unsupported__DOT__gen_sbox__BRA__4__KET____DOT__u_sbox__DOT__unnamedblk10__DOT__unnamedblk11__DOT__unnamedblk12__DOT__unnamedblk13__DOT__k;
        IData/*31:0*/ ascon_top__DOT__gen_unsupported__DOT__gen_sbox__BRA__5__KET____DOT__u_sbox__DOT__unnamedblk1__DOT__fresh_idx;
    };
    struct {
        IData/*31:0*/ ascon_top__DOT__gen_unsupported__DOT__gen_sbox__BRA__5__KET____DOT__u_sbox__DOT__unnamedblk1__DOT__unnamedblk3__DOT__unnamedblk4__DOT__unnamedblk5__DOT__j;
        IData/*31:0*/ ascon_top__DOT__gen_unsupported__DOT__gen_sbox__BRA__5__KET____DOT__u_sbox__DOT__unnamedblk1__DOT__unnamedblk3__DOT__unnamedblk4__DOT__unnamedblk5__DOT__unnamedblk6__DOT__k;
        IData/*31:0*/ ascon_top__DOT__gen_unsupported__DOT__gen_sbox__BRA__5__KET____DOT__u_sbox__DOT__unnamedblk7__DOT__i;
        IData/*31:0*/ ascon_top__DOT__gen_unsupported__DOT__gen_sbox__BRA__5__KET____DOT__u_sbox__DOT__unnamedblk10__DOT__i;
        IData/*31:0*/ ascon_top__DOT__gen_unsupported__DOT__gen_sbox__BRA__5__KET____DOT__u_sbox__DOT__unnamedblk10__DOT__unnamedblk11__DOT__j;
        IData/*31:0*/ ascon_top__DOT__gen_unsupported__DOT__gen_sbox__BRA__5__KET____DOT__u_sbox__DOT__unnamedblk10__DOT__unnamedblk11__DOT__unnamedblk12__DOT__unnamedblk13__DOT__k;
        IData/*31:0*/ __Vfunc_ascon_top__DOT__xor_tree__0__unnamedblk3__DOT__i;
        IData/*31:0*/ __Vfunc_ascon_top__DOT__xor_tree__1__unnamedblk3__DOT__i;
        IData/*31:0*/ __Vfunc_ascon_top__DOT__xor_tree__2__unnamedblk3__DOT__i;
        IData/*31:0*/ __Vfunc_ascon_top__DOT__xor_tree__3__unnamedblk3__DOT__i;
        IData/*31:0*/ __Vfunc_ascon_top__DOT__xor_tree__4__unnamedblk3__DOT__i;
        IData/*31:0*/ __Vfunc_ascon_top__DOT__xor_tree__5__unnamedblk3__DOT__i;
        IData/*31:0*/ __Vfunc_ascon_top__DOT__xor_tree__6__unnamedblk3__DOT__i;
        IData/*31:0*/ __Vfunc_ascon_top__DOT__xor_tree__7__unnamedblk3__DOT__i;
        IData/*31:0*/ __Vfunc_ascon_top__DOT__xor_tree__8__unnamedblk3__DOT__i;
        IData/*31:0*/ __Vfunc_ascon_top__DOT__xor_tree__9__unnamedblk3__DOT__i;
        IData/*31:0*/ __Vfunc_ascon_top__DOT__xor_tree__10__unnamedblk3__DOT__i;
        IData/*31:0*/ __Vfunc_ascon_top__DOT__xor_tree__11__unnamedblk3__DOT__i;
        IData/*31:0*/ __Vfunc_ascon_top__DOT__xor_tree__12__unnamedblk3__DOT__i;
        IData/*31:0*/ __Vfunc_ascon_top__DOT__xor_tree__13__unnamedblk3__DOT__i;
        IData/*31:0*/ __Vfunc_ascon_top__DOT__xor_tree__14__unnamedblk3__DOT__i;
        IData/*31:0*/ __Vfunc_ascon_top__DOT__xor_tree__15__unnamedblk3__DOT__i;
        IData/*31:0*/ __Vfunc_ascon_top__DOT__xor_tree__16__unnamedblk3__DOT__i;
        IData/*31:0*/ __Vfunc_ascon_top__DOT__xor_tree__17__unnamedblk3__DOT__i;
        IData/*31:0*/ __Vfunc_ascon_top__DOT__xor_tree__18__unnamedblk3__DOT__i;
        IData/*31:0*/ __Vfunc_ascon_top__DOT__xor_tree__19__unnamedblk3__DOT__i;
        IData/*31:0*/ __Vfunc_ascon_top__DOT__xor_tree__20__unnamedblk3__DOT__i;
        IData/*31:0*/ __Vfunc_ascon_top__DOT__xor_tree__21__unnamedblk3__DOT__i;
        IData/*31:0*/ __Vfunc_ascon_top__DOT__xor_tree__22__unnamedblk3__DOT__i;
        IData/*31:0*/ __Vfunc_ascon_top__DOT__xor_tree__23__unnamedblk3__DOT__i;
        IData/*31:0*/ __Vfunc_ascon_top__DOT__xor_tree__24__unnamedblk3__DOT__i;
        IData/*31:0*/ __Vfunc_ascon_top__DOT__xor_tree__25__unnamedblk3__DOT__i;
        IData/*31:0*/ __Vfunc_ascon_top__DOT__xor_tree__26__unnamedblk3__DOT__i;
        IData/*31:0*/ __Vfunc_ascon_top__DOT__xor_tree__27__unnamedblk3__DOT__i;
        IData/*31:0*/ __Vfunc_ascon_top__DOT__xor_tree__28__unnamedblk3__DOT__i;
        IData/*31:0*/ __Vfunc_ascon_top__DOT__xor_tree__29__unnamedblk3__DOT__i;
        VlWide<4>/*127:0*/ __Vfunc_ascon_top__DOT__reverse_bytes__30__Vfuncout;
        VlWide<4>/*127:0*/ __Vfunc_ascon_top__DOT__reverse_bytes__30__x;
        VlWide<4>/*127:0*/ __Vfunc_ascon_top__DOT__reverse_bytes__30__y;
        VlWide<4>/*127:0*/ __Vfunc_ascon_top__DOT__reverse_bytes__31__Vfuncout;
        VlWide<4>/*127:0*/ __Vfunc_ascon_top__DOT__reverse_bytes__31__x;
        VlWide<4>/*127:0*/ __Vfunc_ascon_top__DOT__reverse_bytes__31__y;
        IData/*31:0*/ __Vfunc_ascon_top__DOT__gen_unsupported__DOT__gen_sbox__BRA__0__KET____DOT__u_sbox__DOT__xor_tree__42__N;
        IData/*31:0*/ __Vfunc_ascon_top__DOT__gen_unsupported__DOT__gen_sbox__BRA__0__KET____DOT__u_sbox__DOT__xor_tree__42__unnamedblk8__DOT__i;
        IData/*31:0*/ __Vfunc_ascon_top__DOT__gen_unsupported__DOT__gen_sbox__BRA__0__KET____DOT__u_sbox__DOT__xor_tree__42__unnamedblk9__DOT__i;
        IData/*31:0*/ __Vfunc_ascon_top__DOT__gen_unsupported__DOT__gen_sbox__BRA__0__KET____DOT__u_sbox__DOT__xor_tree__42__level;
        IData/*31:0*/ __Vfunc_ascon_top__DOT__gen_unsupported__DOT__gen_sbox__BRA__0__KET____DOT__u_sbox__DOT__xor_tree__42__num;
        IData/*31:0*/ __Vfunc_ascon_top__DOT__gen_unsupported__DOT__gen_sbox__BRA__1__KET____DOT__u_sbox__DOT__xor_tree__43__N;
        IData/*31:0*/ __Vfunc_ascon_top__DOT__gen_unsupported__DOT__gen_sbox__BRA__1__KET____DOT__u_sbox__DOT__xor_tree__43__unnamedblk8__DOT__i;
        IData/*31:0*/ __Vfunc_ascon_top__DOT__gen_unsupported__DOT__gen_sbox__BRA__1__KET____DOT__u_sbox__DOT__xor_tree__43__unnamedblk9__DOT__i;
        IData/*31:0*/ __Vfunc_ascon_top__DOT__gen_unsupported__DOT__gen_sbox__BRA__1__KET____DOT__u_sbox__DOT__xor_tree__43__level;
        IData/*31:0*/ __Vfunc_ascon_top__DOT__gen_unsupported__DOT__gen_sbox__BRA__1__KET____DOT__u_sbox__DOT__xor_tree__43__num;
        IData/*31:0*/ __Vfunc_ascon_top__DOT__gen_unsupported__DOT__gen_sbox__BRA__2__KET____DOT__u_sbox__DOT__xor_tree__44__N;
        IData/*31:0*/ __Vfunc_ascon_top__DOT__gen_unsupported__DOT__gen_sbox__BRA__2__KET____DOT__u_sbox__DOT__xor_tree__44__unnamedblk8__DOT__i;
        IData/*31:0*/ __Vfunc_ascon_top__DOT__gen_unsupported__DOT__gen_sbox__BRA__2__KET____DOT__u_sbox__DOT__xor_tree__44__unnamedblk9__DOT__i;
        IData/*31:0*/ __Vfunc_ascon_top__DOT__gen_unsupported__DOT__gen_sbox__BRA__2__KET____DOT__u_sbox__DOT__xor_tree__44__level;
        IData/*31:0*/ __Vfunc_ascon_top__DOT__gen_unsupported__DOT__gen_sbox__BRA__2__KET____DOT__u_sbox__DOT__xor_tree__44__num;
        IData/*31:0*/ __Vfunc_ascon_top__DOT__gen_unsupported__DOT__gen_sbox__BRA__3__KET____DOT__u_sbox__DOT__xor_tree__45__N;
        IData/*31:0*/ __Vfunc_ascon_top__DOT__gen_unsupported__DOT__gen_sbox__BRA__3__KET____DOT__u_sbox__DOT__xor_tree__45__unnamedblk8__DOT__i;
        IData/*31:0*/ __Vfunc_ascon_top__DOT__gen_unsupported__DOT__gen_sbox__BRA__3__KET____DOT__u_sbox__DOT__xor_tree__45__unnamedblk9__DOT__i;
        IData/*31:0*/ __Vfunc_ascon_top__DOT__gen_unsupported__DOT__gen_sbox__BRA__3__KET____DOT__u_sbox__DOT__xor_tree__45__level;
        IData/*31:0*/ __Vfunc_ascon_top__DOT__gen_unsupported__DOT__gen_sbox__BRA__3__KET____DOT__u_sbox__DOT__xor_tree__45__num;
        IData/*31:0*/ __Vfunc_ascon_top__DOT__gen_unsupported__DOT__gen_sbox__BRA__4__KET____DOT__u_sbox__DOT__xor_tree__46__N;
        IData/*31:0*/ __Vfunc_ascon_top__DOT__gen_unsupported__DOT__gen_sbox__BRA__4__KET____DOT__u_sbox__DOT__xor_tree__46__unnamedblk8__DOT__i;
    };
    struct {
        IData/*31:0*/ __Vfunc_ascon_top__DOT__gen_unsupported__DOT__gen_sbox__BRA__4__KET____DOT__u_sbox__DOT__xor_tree__46__unnamedblk9__DOT__i;
        IData/*31:0*/ __Vfunc_ascon_top__DOT__gen_unsupported__DOT__gen_sbox__BRA__4__KET____DOT__u_sbox__DOT__xor_tree__46__level;
        IData/*31:0*/ __Vfunc_ascon_top__DOT__gen_unsupported__DOT__gen_sbox__BRA__4__KET____DOT__u_sbox__DOT__xor_tree__46__num;
        IData/*31:0*/ __Vfunc_ascon_top__DOT__gen_unsupported__DOT__gen_sbox__BRA__5__KET____DOT__u_sbox__DOT__xor_tree__47__N;
        IData/*31:0*/ __Vfunc_ascon_top__DOT__gen_unsupported__DOT__gen_sbox__BRA__5__KET____DOT__u_sbox__DOT__xor_tree__47__unnamedblk8__DOT__i;
        IData/*31:0*/ __Vfunc_ascon_top__DOT__gen_unsupported__DOT__gen_sbox__BRA__5__KET____DOT__u_sbox__DOT__xor_tree__47__unnamedblk9__DOT__i;
        IData/*31:0*/ __Vfunc_ascon_top__DOT__gen_unsupported__DOT__gen_sbox__BRA__5__KET____DOT__u_sbox__DOT__xor_tree__47__level;
        IData/*31:0*/ __Vfunc_ascon_top__DOT__gen_unsupported__DOT__gen_sbox__BRA__5__KET____DOT__u_sbox__DOT__xor_tree__47__num;
        IData/*31:0*/ __VactIterCount;
        VL_IN64(key1,63,0);
        VL_IN64(key2,63,0);
        VL_IN64(nonce1,63,0);
        VL_IN64(nonce2,63,0);
        VL_IN64(initialVector,63,0);
        VL_IN64(random_masks_sbox,54,0);
        VL_OUT64(tag1,63,0);
        VL_OUT64(tag2,63,0);
        VL_OUT64(debug_state_0,63,0);
        VL_OUT64(debug_state_1,63,0);
        VL_OUT64(debug_state_2,63,0);
        VL_OUT64(debug_state_3,63,0);
        VL_OUT64(debug_state_4,63,0);
        VL_OUT64(debug_round_state_0,63,0);
        VL_OUT64(debug_round_state_1,63,0);
        VL_OUT64(debug_round_state_2,63,0);
        VL_OUT64(debug_round_state_3,63,0);
        VL_OUT64(debug_round_state_4,63,0);
        VL_OUT64(debug_linear_diffusion_state3,63,0);
        VL_OUT64(debug_linear_diffusion_state4,63,0);
        QData/*63:0*/ ascon_top__DOT____VdfgRegularize_h0932e10f_1_0;
        QData/*63:0*/ ascon_top__DOT____VdfgRegularize_h0932e10f_1_1;
        QData/*63:0*/ ascon_top__DOT__state_reg__DOT____Vlvbound_hf68ebc64__1;
        QData/*63:0*/ ascon_top__DOT__state_reg__DOT____Vlvbound_hf68ebc64__2;
        QData/*63:0*/ ascon_top__DOT__state_reg__DOT____Vlvbound_hf68ebc64__3;
        QData/*63:0*/ ascon_top__DOT__state_reg__DOT____Vlvbound_hf68ebc64__4;
        QData/*63:0*/ ascon_top__DOT__key1_reg__DOT__reg_q;
        QData/*63:0*/ ascon_top__DOT__key2_reg__DOT__reg_q;
        QData/*63:0*/ ascon_top__DOT__sipo_reg_x0_debug__DOT__state;
        QData/*63:0*/ ascon_top__DOT__sipo_reg_x0_debug__DOT__next_state;
        QData/*63:0*/ ascon_top__DOT__sipo_reg_x1_debug__DOT__state;
        QData/*63:0*/ ascon_top__DOT__sipo_reg_x1_debug__DOT__next_state;
        QData/*63:0*/ ascon_top__DOT__sipo_reg_x2_debug__DOT__state;
        QData/*63:0*/ ascon_top__DOT__sipo_reg_x2_debug__DOT__next_state;
        QData/*63:0*/ ascon_top__DOT__sipo_reg_x3_debug__DOT__state;
        QData/*63:0*/ ascon_top__DOT__sipo_reg_x3_debug__DOT__next_state;
        QData/*63:0*/ ascon_top__DOT__sipo_reg_x4_debug__DOT__state;
        QData/*63:0*/ ascon_top__DOT__sipo_reg_x4_debug__DOT__next_state;
        QData/*63:0*/ __Vfunc_ascon_top__DOT__rotr64__32__Vfuncout;
        QData/*63:0*/ __Vfunc_ascon_top__DOT__rotr64__32__x;
        QData/*63:0*/ __Vfunc_ascon_top__DOT__rotr64__33__Vfuncout;
        QData/*63:0*/ __Vfunc_ascon_top__DOT__rotr64__33__x;
        QData/*63:0*/ __Vfunc_ascon_top__DOT__rotr64__34__Vfuncout;
        QData/*63:0*/ __Vfunc_ascon_top__DOT__rotr64__34__x;
        QData/*63:0*/ __Vfunc_ascon_top__DOT__rotr64__35__Vfuncout;
        QData/*63:0*/ __Vfunc_ascon_top__DOT__rotr64__35__x;
        QData/*63:0*/ __Vfunc_ascon_top__DOT__rotr64__36__Vfuncout;
        QData/*63:0*/ __Vfunc_ascon_top__DOT__rotr64__36__x;
        QData/*63:0*/ __Vfunc_ascon_top__DOT__rotr64__37__Vfuncout;
        QData/*63:0*/ __Vfunc_ascon_top__DOT__rotr64__37__x;
        QData/*63:0*/ __Vfunc_ascon_top__DOT__rotr64__38__Vfuncout;
        QData/*63:0*/ __Vfunc_ascon_top__DOT__rotr64__38__x;
        QData/*63:0*/ __Vfunc_ascon_top__DOT__rotr64__39__Vfuncout;
        QData/*63:0*/ __Vfunc_ascon_top__DOT__rotr64__39__x;
        QData/*63:0*/ __Vfunc_ascon_top__DOT__rotr64__40__Vfuncout;
    };
    struct {
        QData/*63:0*/ __Vfunc_ascon_top__DOT__rotr64__40__x;
        QData/*63:0*/ __Vfunc_ascon_top__DOT__rotr64__41__Vfuncout;
        QData/*63:0*/ __Vfunc_ascon_top__DOT__rotr64__41__x;
        VlUnpacked<CData/*5:0*/, 11> ascon_top__DOT__rc_block;
        VlUnpacked<IData/*29:0*/, 11> ascon_top__DOT__affine_layer_in;
        VlUnpacked<IData/*29:0*/, 11> ascon_top__DOT__affine_layer_out;
        VlUnpacked<QData/*54:0*/, 6> ascon_top__DOT__next_sbox_input;
        VlUnpacked<QData/*54:0*/, 6> ascon_top__DOT__sbox_input;
        VlUnpacked<QData/*54:0*/, 6> ascon_top__DOT__sbox_output;
        VlUnpacked<QData/*54:0*/, 6> ascon_top__DOT__sbox_output_unmasked;
        VlUnpacked<QData/*54:0*/, 6> ascon_top__DOT__mux_sbox_out;
        VlUnpacked<IData/*29:0*/, 11> ascon_top__DOT__affine_layer2nd_in;
        VlUnpacked<IData/*29:0*/, 11> ascon_top__DOT__affine_layer2nd_out;
        VlUnpacked<QData/*63:0*/, 5> ascon_top__DOT__state_reg_in_absorb;
        VlUnpacked<QData/*63:0*/, 5> ascon_top__DOT__linear_diffusion_debug;
        VlUnpacked<QData/*63:0*/, 5> ascon_top__DOT__state_reg__DOT__state;
        VlUnpacked<QData/*63:0*/, 5> ascon_top__DOT__state_reg__DOT__next_state;
        VlUnpacked<SData/*10:0*/, 5> ascon_top__DOT__gen_unsupported__DOT__gen_sbox__BRA__0__KET____DOT__u_sbox__DOT__x;
        VlUnpacked<VlWide<4>/*120:0*/, 5> ascon_top__DOT__gen_unsupported__DOT__gen_sbox__BRA__0__KET____DOT__u_sbox__DOT__and_result_bank;
        VlUnpacked<VlWide<4>/*120:0*/, 5> ascon_top__DOT__gen_unsupported__DOT__gen_sbox__BRA__0__KET____DOT__u_sbox__DOT__and_result_reg;
        VlUnpacked<SData/*10:0*/, 5> ascon_top__DOT__gen_unsupported__DOT__gen_sbox__BRA__0__KET____DOT__u_sbox__DOT__y;
        VlUnpacked<SData/*10:0*/, 5> ascon_top__DOT__gen_unsupported__DOT__gen_sbox__BRA__0__KET____DOT__u_sbox__DOT__y_noMask;
        VlUnpacked<SData/*10:0*/, 5> ascon_top__DOT__gen_unsupported__DOT__gen_sbox__BRA__1__KET____DOT__u_sbox__DOT__x;
        VlUnpacked<VlWide<4>/*120:0*/, 5> ascon_top__DOT__gen_unsupported__DOT__gen_sbox__BRA__1__KET____DOT__u_sbox__DOT__and_result_bank;
        VlUnpacked<VlWide<4>/*120:0*/, 5> ascon_top__DOT__gen_unsupported__DOT__gen_sbox__BRA__1__KET____DOT__u_sbox__DOT__and_result_reg;
        VlUnpacked<SData/*10:0*/, 5> ascon_top__DOT__gen_unsupported__DOT__gen_sbox__BRA__1__KET____DOT__u_sbox__DOT__y;
        VlUnpacked<SData/*10:0*/, 5> ascon_top__DOT__gen_unsupported__DOT__gen_sbox__BRA__1__KET____DOT__u_sbox__DOT__y_noMask;
        VlUnpacked<SData/*10:0*/, 5> ascon_top__DOT__gen_unsupported__DOT__gen_sbox__BRA__2__KET____DOT__u_sbox__DOT__x;
        VlUnpacked<VlWide<4>/*120:0*/, 5> ascon_top__DOT__gen_unsupported__DOT__gen_sbox__BRA__2__KET____DOT__u_sbox__DOT__and_result_bank;
        VlUnpacked<VlWide<4>/*120:0*/, 5> ascon_top__DOT__gen_unsupported__DOT__gen_sbox__BRA__2__KET____DOT__u_sbox__DOT__and_result_reg;
        VlUnpacked<SData/*10:0*/, 5> ascon_top__DOT__gen_unsupported__DOT__gen_sbox__BRA__2__KET____DOT__u_sbox__DOT__y;
        VlUnpacked<SData/*10:0*/, 5> ascon_top__DOT__gen_unsupported__DOT__gen_sbox__BRA__2__KET____DOT__u_sbox__DOT__y_noMask;
        VlUnpacked<SData/*10:0*/, 5> ascon_top__DOT__gen_unsupported__DOT__gen_sbox__BRA__3__KET____DOT__u_sbox__DOT__x;
        VlUnpacked<VlWide<4>/*120:0*/, 5> ascon_top__DOT__gen_unsupported__DOT__gen_sbox__BRA__3__KET____DOT__u_sbox__DOT__and_result_bank;
        VlUnpacked<VlWide<4>/*120:0*/, 5> ascon_top__DOT__gen_unsupported__DOT__gen_sbox__BRA__3__KET____DOT__u_sbox__DOT__and_result_reg;
        VlUnpacked<SData/*10:0*/, 5> ascon_top__DOT__gen_unsupported__DOT__gen_sbox__BRA__3__KET____DOT__u_sbox__DOT__y;
        VlUnpacked<SData/*10:0*/, 5> ascon_top__DOT__gen_unsupported__DOT__gen_sbox__BRA__3__KET____DOT__u_sbox__DOT__y_noMask;
        VlUnpacked<SData/*10:0*/, 5> ascon_top__DOT__gen_unsupported__DOT__gen_sbox__BRA__4__KET____DOT__u_sbox__DOT__x;
        VlUnpacked<VlWide<4>/*120:0*/, 5> ascon_top__DOT__gen_unsupported__DOT__gen_sbox__BRA__4__KET____DOT__u_sbox__DOT__and_result_bank;
        VlUnpacked<VlWide<4>/*120:0*/, 5> ascon_top__DOT__gen_unsupported__DOT__gen_sbox__BRA__4__KET____DOT__u_sbox__DOT__and_result_reg;
        VlUnpacked<SData/*10:0*/, 5> ascon_top__DOT__gen_unsupported__DOT__gen_sbox__BRA__4__KET____DOT__u_sbox__DOT__y;
        VlUnpacked<SData/*10:0*/, 5> ascon_top__DOT__gen_unsupported__DOT__gen_sbox__BRA__4__KET____DOT__u_sbox__DOT__y_noMask;
        VlUnpacked<SData/*10:0*/, 5> ascon_top__DOT__gen_unsupported__DOT__gen_sbox__BRA__5__KET____DOT__u_sbox__DOT__x;
        VlUnpacked<VlWide<4>/*120:0*/, 5> ascon_top__DOT__gen_unsupported__DOT__gen_sbox__BRA__5__KET____DOT__u_sbox__DOT__and_result_bank;
        VlUnpacked<VlWide<4>/*120:0*/, 5> ascon_top__DOT__gen_unsupported__DOT__gen_sbox__BRA__5__KET____DOT__u_sbox__DOT__and_result_reg;
        VlUnpacked<SData/*10:0*/, 5> ascon_top__DOT__gen_unsupported__DOT__gen_sbox__BRA__5__KET____DOT__u_sbox__DOT__y;
        VlUnpacked<SData/*10:0*/, 5> ascon_top__DOT__gen_unsupported__DOT__gen_sbox__BRA__5__KET____DOT__u_sbox__DOT__y_noMask;
        VlUnpacked<SData/*10:0*/, 5> __Vfunc_ascon_top__DOT__xor_tree__0__stage;
        VlUnpacked<SData/*10:0*/, 5> __Vfunc_ascon_top__DOT__xor_tree__1__stage;
        VlUnpacked<SData/*10:0*/, 5> __Vfunc_ascon_top__DOT__xor_tree__2__stage;
        VlUnpacked<SData/*10:0*/, 5> __Vfunc_ascon_top__DOT__xor_tree__3__stage;
        VlUnpacked<SData/*10:0*/, 5> __Vfunc_ascon_top__DOT__xor_tree__4__stage;
        VlUnpacked<SData/*10:0*/, 5> __Vfunc_ascon_top__DOT__xor_tree__5__stage;
        VlUnpacked<SData/*10:0*/, 5> __Vfunc_ascon_top__DOT__xor_tree__6__stage;
        VlUnpacked<SData/*10:0*/, 5> __Vfunc_ascon_top__DOT__xor_tree__7__stage;
        VlUnpacked<SData/*10:0*/, 5> __Vfunc_ascon_top__DOT__xor_tree__8__stage;
        VlUnpacked<SData/*10:0*/, 5> __Vfunc_ascon_top__DOT__xor_tree__9__stage;
        VlUnpacked<SData/*10:0*/, 5> __Vfunc_ascon_top__DOT__xor_tree__10__stage;
        VlUnpacked<SData/*10:0*/, 5> __Vfunc_ascon_top__DOT__xor_tree__11__stage;
        VlUnpacked<SData/*10:0*/, 5> __Vfunc_ascon_top__DOT__xor_tree__12__stage;
        VlUnpacked<SData/*10:0*/, 5> __Vfunc_ascon_top__DOT__xor_tree__13__stage;
        VlUnpacked<SData/*10:0*/, 5> __Vfunc_ascon_top__DOT__xor_tree__14__stage;
        VlUnpacked<SData/*10:0*/, 5> __Vfunc_ascon_top__DOT__xor_tree__15__stage;
        VlUnpacked<SData/*10:0*/, 5> __Vfunc_ascon_top__DOT__xor_tree__16__stage;
    };
    struct {
        VlUnpacked<SData/*10:0*/, 5> __Vfunc_ascon_top__DOT__xor_tree__17__stage;
        VlUnpacked<SData/*10:0*/, 5> __Vfunc_ascon_top__DOT__xor_tree__18__stage;
        VlUnpacked<SData/*10:0*/, 5> __Vfunc_ascon_top__DOT__xor_tree__19__stage;
        VlUnpacked<SData/*10:0*/, 5> __Vfunc_ascon_top__DOT__xor_tree__20__stage;
        VlUnpacked<SData/*10:0*/, 5> __Vfunc_ascon_top__DOT__xor_tree__21__stage;
        VlUnpacked<SData/*10:0*/, 5> __Vfunc_ascon_top__DOT__xor_tree__22__stage;
        VlUnpacked<SData/*10:0*/, 5> __Vfunc_ascon_top__DOT__xor_tree__23__stage;
        VlUnpacked<SData/*10:0*/, 5> __Vfunc_ascon_top__DOT__xor_tree__24__stage;
        VlUnpacked<SData/*10:0*/, 5> __Vfunc_ascon_top__DOT__xor_tree__25__stage;
        VlUnpacked<SData/*10:0*/, 5> __Vfunc_ascon_top__DOT__xor_tree__26__stage;
        VlUnpacked<SData/*10:0*/, 5> __Vfunc_ascon_top__DOT__xor_tree__27__stage;
        VlUnpacked<SData/*10:0*/, 5> __Vfunc_ascon_top__DOT__xor_tree__28__stage;
        VlUnpacked<SData/*10:0*/, 5> __Vfunc_ascon_top__DOT__xor_tree__29__stage;
        VlUnpacked<SData/*10:0*/, 5> __Vfunc_ascon_top__DOT__gen_unsupported__DOT__gen_sbox__BRA__0__KET____DOT__u_sbox__DOT__xor_tree__42__stage;
        VlUnpacked<SData/*10:0*/, 5> __Vfunc_ascon_top__DOT__gen_unsupported__DOT__gen_sbox__BRA__1__KET____DOT__u_sbox__DOT__xor_tree__43__stage;
        VlUnpacked<SData/*10:0*/, 5> __Vfunc_ascon_top__DOT__gen_unsupported__DOT__gen_sbox__BRA__2__KET____DOT__u_sbox__DOT__xor_tree__44__stage;
        VlUnpacked<SData/*10:0*/, 5> __Vfunc_ascon_top__DOT__gen_unsupported__DOT__gen_sbox__BRA__3__KET____DOT__u_sbox__DOT__xor_tree__45__stage;
        VlUnpacked<SData/*10:0*/, 5> __Vfunc_ascon_top__DOT__gen_unsupported__DOT__gen_sbox__BRA__4__KET____DOT__u_sbox__DOT__xor_tree__46__stage;
        VlUnpacked<SData/*10:0*/, 5> __Vfunc_ascon_top__DOT__gen_unsupported__DOT__gen_sbox__BRA__5__KET____DOT__u_sbox__DOT__xor_tree__47__stage;
        VlUnpacked<CData/*0:0*/, 5> __Vm_traceActivity;
    };
    VlTriggerVec<1> __VstlTriggered;
    VlTriggerVec<1> __VicoTriggered;
    VlTriggerVec<2> __VactTriggered;
    VlTriggerVec<2> __VnbaTriggered;

    // INTERNAL VARIABLES
    Vascon_top__Syms* const vlSymsp;

    // PARAMETERS
    static constexpr VlUnpacked<IData/*31:0*/, 5> ascon_top__DOT__rotations_a = {{
        0x00000013U, 0x0000003dU, 0x00000001U, 0x0000000aU,
        0x00000007U
    }};
    static constexpr VlUnpacked<IData/*31:0*/, 5> ascon_top__DOT__rotations_b = {{
        0x0000001cU, 0x00000027U, 0x00000006U, 0x00000011U,
        0x00000029U
    }};

    // CONSTRUCTORS
    Vascon_top___024root(Vascon_top__Syms* symsp, const char* v__name);
    ~Vascon_top___024root();
    VL_UNCOPYABLE(Vascon_top___024root);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
};


#endif  // guard
